# This Makefile should need no changes from webwml/english/ports/sparc64/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/sparc64
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/sparc64/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
