#use wml::debian::submenu
#include "$(ENGLISHDIR)/international/l10n/menu.def"

<define-menu-item name="l10n"><menu-l10n></define-menu-item>
<define-menu-item name="list"><menu-list></define-menu-item>
<define-menu-item name="rank"><menu-rank></define-menu-item>
<define-menu-item name="todo"><menu-todo></define-menu-item>

<menu-item name="l10n"          basename="../">
<menu-item name="list"          basename="./">
<menu-item name="rank"          basename="rank">
<menu-item name="todo"          basename="todo">

