#   Translators, do not translate nor copy this file

<h3><pkg-section main></h3>
<!-- BEGIN SECTION -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todol-main -->
</podebconf-table-status>
<!-- END SECTION -->
<!-- BEGIN SECTION -->
<po-table>
<!-- DO NOT REMOVE THIS LINE: todo-main -->
</po-table>
<!-- END SECTION -->

<h3><pkg-section contrib></h3>
<!-- BEGIN SECTION -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todol-contrib -->
</podebconf-table-status>
<!-- END SECTION -->
<!-- BEGIN SECTION -->
<po-table>
<!-- DO NOT REMOVE THIS LINE: todo-contrib -->
</po-table>
<!-- END SECTION -->

<h3><pkg-section non-free></h3>
<!-- BEGIN SECTION -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todol-non-free -->
</podebconf-table-status>
<!-- END SECTION -->
<!-- BEGIN SECTION -->
<po-table>
<!-- DO NOT REMOVE THIS LINE: todo-non-free -->
</po-table>
<!-- END SECTION -->
