# This Makefile should need no changes from webwml/english/2.0/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=releases/slink
SUBS=

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: ../../../english/releases/slink/formats_and_architectures.wmh \
			$(TEMPLDIR)/languages.wml $(TEMPLDIR)/install_manual.wml
