# This Makefile should need no changes from webwml/english/ports/m68k/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/m68k
SUBS=

include $(WMLBASE)/Make.lang

