# This Makefile should need no changes from webwml/english/ports/alpha/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/s390
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/s390/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
