#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="s390">
   [EN:Debian for S/390:]
   [AR:Debian for S/390:]
   [DA:Debian til S/390:]
   [DE:Debian für S/390:]
   [EL:Debian for S/390:]
   [EO:Debian for S/390:]
   [ES:Debian para S/390:]
   [FI:Debian for S/390:]
   [FR:Debian for S/390:]
   [HR:Debian for S/390:]
   [HU:Debian for S/390:]
   [IT:Debian per S/390:]
   [JA:Debian for S/390:]
   [KO:Debian for S/390:]
   [NL:Debian for S/390:]
   [NO:Debian for S/390:]
   [PL:Debian for S/390:]
   [PT:Debian para S/390:]
   [RO:Debian for S/390:]
   [RU:Debian for S/390:]
   [SV:Debian för S/390:]
   [TR:Debian for S/390:]
   [ZH:Debian for S/390:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="s390"          basename="index">
<menu-item name="news"          basename="news">

