# This Makefile should need no changes from webwml/english/ports/powerpc/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/powerpc
SUBS=inst pics

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml menu.inc $(TEMPLDIR)/template.wml
devel.$(LANGUAGE).html: devel.wml menu.inc $(TEMPLDIR)/template.wml
docu.$(LANGUAGE).html: docu.wml menu.inc $(TEMPLDIR)/template.wml
history.$(LANGUAGE).html: history.wml menu.inc $(TEMPLDIR)/template.wml
news.$(LANGUAGE).html: news.wml menu.inc $(TEMPLDIR)/template.wml
supply.$(LANGUAGE).html: supply.wml menu.inc $(TEMPLDIR)/template.wml
