# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=ports/powerpc
SUBS=inst pics

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/powerpc/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
