#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="powerpc">
   [EN:Debian for PowerPC:]
   [AR:Debian for PowerPC:]
   [DA:Debian til PowerPC:]
   [DE:Debian für PowerPC:]
   [EL:Debian for PowerPC:]
   [EO:Debian for PowerPC:]
   [ES:Debian para PowerPC:]
   [FI:Debian for PowerPC:]
   [FR:Debian pour PowerPC:]
   [HR:Debian za PowerPC:]
   [HU:Debian for PowerPC:]
   [IT:Debian per PowerPC:]
   [JA:Debian for PowerPC:]
   [KO:Debian for PowerPC:]
   [NL:Debian for PowerPC:]
   [NO:Debian for PowerPC:]
   [PL:Debian for PowerPC:]
   [PT:Debian para PowerPC:]
   [RO:Debian for PowerPC:]
   [RU:Debian for PowerPC:]
   [SV:Debian för PowerPC:]
   [TR:Debian for PowerPC:]
   [ZH:Debian for PowerPC:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="powerpc"       basename="index">
<menu-item name="install"       basename="inst/install">
<menu-item name="doc"           basename="docu">
<menu-item name="devel"         basename="devel">
