#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="ia64">
   [EN:Debian for IA-64:]
   [AR:Debian for IA-64:]
   [CA:Debian per a IA-64:]
   [DA:Debian til IA-64:]
   [DE:Debian für IA-64:]
   [EL:Debian for IA-64:]
   [EO:Debian for IA-64:]
   [ES:Debian para IA-64:]
   [FI:Debian for IA-64:]
   [FR:Debian pour IA-64:]
   [HR:Debian for IA-64:]
   [HU:Debian for IA-64:]
   [IT:Debian per IA-64:]
   [JA:Debian for IA-64:]
   [KO:Debian for IA-64:]
   [NL:Debian for IA-64:]
   [NO:Debian for IA-64:]
   [PL:Debian for IA-64:]
   [PT:Debian para IA-64:]
   [RO:Debian for IA-64:]
   [RU:Debian for IA-64:]
   [SV:Debian för IA-64:]
   [TR:Debian for IA-64:]
   [ZH:Debian for IA-64:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="ia64"          basename="index">
<menu-item name="news"          basename="news">

