# This Makefile should need no changes from webwml/english/intro/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=intro
SUBS=

include $(WMLBASE)/Make.lang


organization.$(LANGUAGE).html: organization.wml \
  $(ENGLISHSRCDIR)/intro/organization.data \
  $(ENGLISHSRCDIR)/intro/organization.tags
