# This Makefile should need no changes from webwml/english/ports/mips/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/mips
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml menu.inc $(TEMPLDIR)/template.wml
cpu.$(LANGUAGE).html: cpu.wml menu.inc $(TEMPLDIR)/template.wml
system.$(LANGUAGE).html: system.wml menu.inc $(TEMPLDIR)/template.wml