# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=ports/mips
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: $(ENGLISHSRCDIR)/ports/mips/people.inc
