#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"


<define-menu-item name="mips">
  <gettext domain="ports">Debian for MIPS</gettext>
</define-menu-item>

<define-tag email>&lt;<A href="mailto:%0">%0</A>&gt;</define-tag>

<menu-item name="ports"         basename="../index">
<menu-item name="mips"          basename="index">
<menu-item name="cpu"           basename="cpu">
<menu-item name="news"          basename="news">
<menu-item name="systems"       basename="system">

