#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="mips">
   [EN:Debian for MIPS:]
   [AR:Debian for MIPS:]
   [DA:Debian til MIPS:]
   [DE:Debian für MIPS:]
   [EL:Debian for MIPS:]
   [EO:Debian for MIPS:]
   [ES:Debian para MIPS:]
   [FI:Debian for MIPS:]
   [FR:Debian for MIPS:]
   [HR:Debian for MIPS:]
   [HU:Debian for MIPS:]
   [IT:Debian per MIPS:]
   [JA:Debian for MIPS:]
   [KO:Debian for MIPS:]
   [NL:Debian for MIPS:]
   [NO:Debian for MIPS:]
   [PL:Debian for MIPS:]
   [PT:Debian para MIPS:]
   [RO:Debian for MIPS:]
   [RU:Debian for MIPS:]
   [SV:Debian för MIPS:]
   [TR:Debian for MIPS:]
   [ZH:Debian for MIPS:]
</define-menu-item>

<define-tag email>&lt;<A href="mailto:%0">%0</A>&gt;</define-tag>

<menu-item name="ports"         basename="../index">
<menu-item name="mips"          basename="index">
<menu-item name="cpu"           basename="cpu">
<menu-item name="news"          basename="news">
<menu-item name="systems"       basename="system">

