<ul>
<li> Ryan Murray, <email rmurray@debian.org><br>
<li> Guido Guenther, <email guido.guenther@gmx.net><br>
<li> Christoph Martin, <email martin@uni-mainz.de><br>
<li> Florian Lohoff, <email flo@rfc822.org><br>
<li> Henning Heinold, <email heinold@physik.tu-cottbus.de><br>
<li> Martin Michlmayr, <email tbm@cyrius.com><br>
<li> Ulf Carlsson, <email ulfc@calypso.engr.sgi.com><br>
<li> Vincent Renardias, <email vincent@debian.org><br>
<li> Karsten Merker, <email merker@linuxtag.org><br>
<li> Martin Schulze, <email joey@debian.org><br>
</ul>
