{#style#:
      <style type="text/css">
      <!--
      body { background: #fff; color: #000; }
      a:link,a:visited,a:active { background: #0ff; color: #006; }
      #foot { font-size: x-small; }
      .n0 { background: #eee }
      .n1 { background: #cee }
      .n2 { background: #aee }
      .n3 { background: #ece }
      .n4 { background: #cce }
      .n5 { background: #ace }
      .n6 { background: #eae }
      .n7 { background: #cae }
      .n8 { background: #aae }
      .n9 { background: #eec }
      .n10 { background: #cec }
      .n11 { background: #aec }
      .n12 { background: #ecc }
      .n13 { background: #ccc }
      .n14 { background: #acc }
      .n15 { background: #eac }
      .n16 { background: #cac }
      .n17 { background: #aac }
      .n18 { background: #eea }
      .n19 { background: #cea }
      .n20 { background: #aea }
      .n21 { background: #eca }
      .n22 { background: #cca }
      .n23 { background: #aca }
      .n24 { background: #eaa }
      .n25 { background: #caa }
      .n26 { background: #aaa }
      .meta { color: #999 }
      // -->
      </style>
:##}
