<p>Autres pages concernant le système de gestion des bogues (SGB ou BTS pour <i>Bug Tracking System</i> en anglais)&nbsp;:

<ul>
  <li><a href="./">Page principale du système de gestion des bogues.</a>
  <li><a href="Reporting">Instructions pour signaler des bogues.</a>
  <li><a href="Access">Accéder aux enregistrements de bogues autrement que
	sur la Toile.</a>
  <li><a href="Developer">Informations pour les développeurs 
	sur le système de gestion des bogues.</a>
  <li><a href="server-control">Informations pour les développeurs
	sur le traitement des bogues par messagerie électronique.</a>
  <li><a href="server-refcard">Carte de référence des serveurs de 
	messagerie.</a>
  <li><a href="server-request">Requêtes de rapport de bogues par
	messages électroniques.</a>
#  <li><a href="db/ix/full.html">Liste complète des rapports de bogues
# non résolus et récents.</a>
#  <li><a href="db/ix/packages.html">Paquets ayant des rapports de bogues.</a>
#  <li><a href="db/ix/maintainers.html">Mainteneurs de paquets ayant des
# rapports de bogues.</a>
</ul>
