# This Makefile should need no changes from
# the file webwml/english/devel/debian-volatile/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=devel/debian-volatile
#SUBS=News

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/template.wml \
  $(TEMPLDIR)/recent_list.wml
#  $(TEMPLDIR)/recent_list.wml \
#  $(wildcard News/[0-9]*/*.wml) \
#  $(wildcard $(ENGLISHSRCDIR)/$(CUR_DIR)/News/[0-9]*/*.wml)
