# This Makefile should need no changes from webwml/english/misc/laptops/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=misc/laptops
SUBS=

GETTEXTFILES += ports.mo

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/misc/laptops/menu.inc \
  $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml $(GETTEXTDEP)
