#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="laptops">
   [EN:Debian for Laptops:]
   [AR:Debian for Laptops:]
   [CA:Debian per a portàtils:]
   [DA:Debian til bærbare:]
   [DE:Debian für Laptops:]
   [EL:Debian for Laptops:]
   [EO:Debian for Laptops:]
   [ES:Debian para portátiles:]
   [FI:Debian for Laptops:]
   [FR:Debian pour portables:]
   [HR:Debian za laptope:]
   [HU:Debian for Laptops:]
   [IT:Debian per Laptops:]
   [JA:Debian for Laptops:]
   [KO:Debian for Laptops:]
   [NL:Debian for Laptops:]
   [NO:Debian for Laptops:]
   [PL:Debian for Laptops:]
   [PT:Debian para Laptops:]
   [RO:Debian for Laptops:]
   [RU:Debian for Laptops:]
   [SV:Debian för bärbara:]
   [TR:Debian for Laptops:]
   [ZH:Debian for Laptops:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="laptops"       basename="index">

