# This Makefile should need no changes from webwml/chinese/international/Chinese/News/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../..
CUR_DIR=international/Chinese/News
SUBS=
ZHTEMPLATE=$(WMLBASE)/template/debian-zh/template.tmpl

include $(WMLBASE)/Make.lang

