<p>Other BTS pages:</p>

<ul>
  <li><a href="./">Bug tracking system main contents page.</a></li>
  <li><a href="Reporting">Instructions for reporting bugs.</a></li>
  <li><a href="Access">Accessing the bug tracking system logs.</a></li>
  <li><a href="Developer">Information for developers on the bug tracking
      system.</a></li>
  <li><a href="server-control">Developers' information on manipulation
      of bugs using the e-mail control interface.</a></li>
  <li><a href="server-refcard">Mailservers' reference card.</a></li>
  <li><a href="server-request">Requesting bug reports by e-mail.</a></li>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a></li>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a></li>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a></li>
</ul>
