include $(subst webwml/japanese,webwml/english,$(CURDIR))/Makefile

ZHTEMPLATEDIR = $(WMLBASE)/international/Chinese/template/debian-zh
ZHTEMPLATE = $(ZHTEMPLATEDIR)/template.tmpl
$(ZHTEMPLATE): $(TEMPLDIR)/template.wml \
 $(ZHTEMPLATEDIR)/macros.tmpl $(ZHTEMPLATEDIR)/navbar.tmpl
