# This Makefile should need no changes from webwml/chinese/chinese/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=chinese/debian-doc
# list any subdirectories in the following variable. Any directories listed
# must exist or the make will not work
SUBS=FAQ
ZHTEMPLATE=$(WMLBASE)/template/debian-zh/template.tmpl

include $(WMLBASE)/Make.lang
include $(WMLBASE)/Make.common

include $(WMLBASE)/Make.dep.templ    
include $(WMLBASE)/Make.dep.generic

