<?
    $iso = array("US" => "United States of America",
        "CA" => "Canada",
        "JP" => "Japan",
        "GB" => "United Kingdom",
        "AU" => "Australia",
        "DE" => "Germany",
        "FR" => "France",
        "CH" => "Switzerland",
        "IT" => "Italy",
        "NL" => "Netherlands",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AI" => "Anguilla",
        "AQ" => "Antartica",
        "AG" => "Antigua & Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "IO" => "British Indian Ocean Terr.",
        "BN" => "Brunei Darussalam",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos (Keeling) Isl",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo",
        "CK" => "Cook Isl",
        "CR" => "Costa Rica",
        "CI" => "Cote D'Ivoire",
        "HR" => "Croatia",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "TP" => "East Timor",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FO" => "Faeroe Islands",
        "FK" => "Falkland Isl. (Malvinas)",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Terr.",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey, C.I.",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard and McDonald Isl",
        "HN" => "Honduras",
        "HK" => "Hong Kong",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey, C.I.",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KR" => "Korea, Republic of",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxemborg",
        "MO" => "Macau",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Isl",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MD" => "Moldova, Republic of",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "AN" => "Netherland Antilles",
        "NL" => "Netherlands",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Isl",
        "MP" => "Northern Mariana Isl",
        "NO" => "Norway",
        "OM" => "Oman",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PA" => "Panama",
        "PZ" => "Panama Canal Zone",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RE" => "Reunion",
        "RO" => "Romania",
        "RU" => "Russian Federation",
        "RW" => "Rwanda",
        "KN" => "Saint Kitts & Nevis",
        "LC" => "Saint Lucia",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "Sao Tome & Principe",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SH" => "St. Helena",
        "PM" => "St. Pierre and Miquelon",
        "VC" => "St. Vincent & Grenadines",
        "SR" => "Suriname",
        "SJ" => "Svalbard & Jan Mayen Isl",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania, United Republic ",
        "TH" => "Thailand",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad & Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Isl",
        "TV" => "Tuvalu",
        "AE" => "U.A.E.",
        "UM" => "U.S.Minor Outlying Isl",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "GB" => "United Kingdom",
        "US" => "United States",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City State",
        "VE" => "Venezuela",
        "VN" => "Viet Nam",
        "VG" => "Virgin Isl (British)",
        "VI" => "Virgin Isl, (U.S.)",
        "WF" => "Wallis & Futuna Islands",
        "EH" => "Western Sahara",
        "YE" => "Yemen, Republic of",
        "ZR" => "Zaire",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe");

    function print_place($begin, $finish, $city, $country) {
        $country = $iso[$country];
        if ($city) {
            echo "<LI>$city, $country: ";
        } else {
            echo "<LI>$country: ";
        }
        if (! $begin && ! $finish) {
            echo "always";
        } else if ($begin && ! $finish) {
            echo "starting on $begin";
        } else if (! $begin && $finish) {
            echo "until $finish";
        } else {
            echo "$begin to $finish";
        }
    }

    function print_all_places($id, $modify) {

        if (!($db = open_db())) {
            echo "Cannot open SQL database";
            return FALSE;
        }

        $sql = "SELECT id, begin, finish, city, country FROM places WHERE who = '$id' ORDER BY begin, finish";
        if (! ($query = pg_exec($db, $sql))) {
            echo "Problem with query", pg_ErrorMessage($db), "<BR>";
            return FALSE;
        }
        echo "<UL>";
        $rows = pg_NumRows($query);
        for ($i = 0; $i < $rows; $i++) {
            $row = pg_Fetch_Array($query, $i);
            print_place($row["begin"], $row["finish"], $row["city"], $row["country"]);
            if ($modify) {
                echo " <A HREF = \"gpgplace.php?id=", $row["id"], "\">[Modify]</A>";
                echo " <A HREF = \"gpgplace.php?remove=1&id=", $row["id"], "\">[Remove]</A>";
            }
        }
        echo "</UL>";
    }


    function print_people($db, $sql) {
        if (! ($query = pg_exec($db, $sql))) {
            echo "Problem with query", pg_ErrorMessage($db), "<BR>";
            return FALSE;
        }
        $rows = pg_NumRows($query);
        for ($i = 0; $i < $rows; $i++) {
            $row = pg_Fetch_Array($query, $i);
            echo "<H2>";
            echo $row["forename"], " ", $row["surname"];
            echo " &lt;", $row["email"], "&gt;";
            echo "</H2>\n";

            print_all_places($row["id"], FALSE);

        }
    }

?>

