#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"


<define-menu-item name="alpha">
  <gettext domain="ports">Debian for Alpha</gettext>
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="alpha"         basename="index">
<menu-item name="news"          basename="news">
<menu-item name="status"        basename="port-status">
<menu-item name="systems"       basename="sys_types">
<menu-item name="links"         basename="links">

