# This Makefile should need no changes from webwml/english/y2k/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=y2k
# list any subdirectories in the following variable. Any directories listed
# must exist or the make will not work
SUBS=

include $(WMLBASE)/Make.lang
include $(WMLBASE)/Make.common

include $(WMLBASE)/Make.dep.templ    
include $(WMLBASE)/Make.dep.generic

index.$(LANGUAGE).html: ../../english/y2k/index.data
extra.$(LANGUAGE).html: ../../english/y2k/extra.data
