# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=..
CUR_DIR=y2k
SUBS=

GETTEXTFILES += others.mo

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: ../../english/y2k/index.data
extra.$(LANGUAGE).html: ../../english/y2k/extra.data
