# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=blends/hamradio
SUBS=News Pics get docs

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc

about.$(LANGUAGE).html: about.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc

dev.$(LANGUAGE).html: dev.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc

contact.$(LANGUAGE).html: contact.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc

support.$(LANGUAGE).html: support.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc

fun.$(LANGUAGE).html: fun.wml $(TEMPLDIR)/blend.wml $(TEMPLDIR)/template.wml $(TEMPLDIR)/basic.wml navbar.inc
