# This Makefile should need no changes from webwml/english/CD/netinst/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=CD/netinst
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/template.wml \
  $(ENGLISHSRCDIR)/releases/info $(TEMPLDIR)/installer.wml
