#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="netbsd-i386">
   [EN:Debian GNU/NetBSD for i386:]
   [AR:Debian GNU/NetBSD for i386:]
   [DA:Debian GNU/NetBSD til i386:]
   [DE:Debian GNU/NetBSD für i386:]
   [EL:Debian GNU/NetBSD for i386:]
   [EO:Debian GNU/NetBSD for i386:]
   [ES:Debian GNU/NetBSD para i386:]
   [FI:Debian GNU/NetBSD for i386:]
   [FR:Debian GNU/NetBSD pour i386:]
   [HR:Debian GNU/NetBSD for i386:]
   [HU:Debian GNU/NetBSD for i386:]
   [IT:Debian GNU/NetBSD per i386:]
   [JA:Debian GNU/NetBSD for i386:]
   [KO:Debian GNU/NetBSD for i386:]
   [NL:Debian GNU/NetBSD for i386:]
   [NO:Debian GNU/NetBSD for i386:]
   [PL:Debian GNU/NetBSD for i386:]
   [PT:Debian GNU/NetBSD para i386:]
   [RO:Debian GNU/NetBSD for i386:]
   [RU:Debian GNU/NetBSD for i386:]
   [SV:Debian GNU/NetBSD för i386:]
   [TR:Debian GNU/NetBSD for i386:]
   [ZH:Debian GNU/NetBSD for i386:]
</define-menu-item>

<define-menu-item name="netbsd-alpha">
   [EN:Debian GNU/NetBSD for Alpha:]
   [AR:Debian GNU/NetBSD for Alpha:]
   [DA:Debian GNU/NetBSD til Alpha:]
   [DE:Debian GNU/NetBSD für Alpha:]
   [EL:Debian GNU/NetBSD for Alpha:]
   [EO:Debian GNU/NetBSD for Alpha:]
   [ES:Debian GNU/NetBSD para Alpha:]
   [FI:Debian GNU/NetBSD for Alpha:]
   [FR:Debian GNU/NetBSD pour Alpha:]
   [HR:Debian GNU/NetBSD for Alpha:]
   [HU:Debian GNU/NetBSD for Alpha:]
   [IT:Debian GNU/NetBSD per Alpha:]
   [JA:Debian GNU/NetBSD for Alpha:]
   [KO:Debian GNU/NetBSD for Alpha:]
   [NL:Debian GNU/NetBSD for Alpha:]
   [NO:Debian GNU/NetBSD for Alpha:]
   [PL:Debian GNU/NetBSD for Alpha:]
   [PT:Debian GNU/NetBSD para Alpha:]
   [RO:Debian GNU/NetBSD for Alpha:]
   [RU:Debian GNU/NetBSD for Alpha:]
   [SV:Debian GNU/NetBSD för Alpha:]
   [TR:Debian GNU/NetBSD for Alpha:]
   [ZH:Debian GNU/NetBSD for Alpha:]
</define-menu-item>

<define-menu-item name="why">
   [EN:Why:]
   [AR:Why:]
   [DA:Hvorfor:]
   [DE:Weshalb:]
   [EL:Why:]
   [EO:Why:]
   [ES:Why:]
   [FI:Why:]
   [FR:Pourquoi:]
   [HR:Why:]
   [HU:Why:]
   [IT:Why:]
   [JA:Why:]
   [KO:Why:]
   [NL:Why:]
   [NO:Why:]
   [PL:Why:]
   [PT:Why:]
   [RO:Why:]
   [RU:Why:]
   [SV:Why:]
   [TR:Why:]
   [ZH:Why:]
</define-menu-item>

<define-menu-item name="people">
   [EN:People:]
   [AR:People:]
   [DA:Folk:]
   [DE:Leute:]
   [EL:People:]
   [EO:People:]
   [ES:People:]
   [FI:People:]
   [FR:People:]
   [HR:People:]
   [HU:People:]
   [IT:People:]
   [JA:People:]
   [KO:People:]
   [NL:People:]
   [NO:People:]
   [PL:People:]
   [PT:People:]
   [RO:People:]
   [RU:People:]
   [SV:People:]
   [TR:People:]
   [ZH:People:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="netbsd-i386"   basename="index">
<menu-item name="netbsd-alpha"  basename="alpha">
<menu-item name="news"          basename="news">
<menu-item name="why"           basename="why">
<menu-item name="people"	basename="people">
