# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=ports/hurd
SUBS=extra-files

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/hurd/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
