# This Makefile should need no changes from webwml/english/ports/mips/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/hurd
SUBS=reference-manual extra-files

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml menu.inc $(TEMPLDIR)/template.wml
hurd-cd.$(LANGUAGE).html: hurd-cd.wml menu.inc $(TEMPLDIR)/template.wml
hurd-contact.$(LANGUAGE).html: hurd-contact.wml menu.inc $(TEMPLDIR)/template.wml
hurd-devel-debian.$(LANGUAGE).html: hurd-devel-debian.wml menu.inc $(TEMPLDIR)/template.wml
hurd-devel-ports.$(LANGUAGE).html: hurd-devel-ports.wml menu.inc $(TEMPLDIR)/template.wml
hurd-devel-tasks.$(LANGUAGE).html: hurd-devel-tasks.wml menu.inc $(TEMPLDIR)/template.wml
hurd-devel.$(LANGUAGE).html: hurd-devel.wml menu.inc $(TEMPLDIR)/template.wml
hurd-doc-server.$(LANGUAGE).html: hurd-doc-server.wml menu.inc $(TEMPLDIR)/template.wml
hurd-doc-translator.$(LANGUAGE).html: hurd-doc-translator.wml menu.inc $(TEMPLDIR)/template.wml
hurd-doc-utils.$(LANGUAGE).html: hurd-doc-utils.wml menu.inc $(TEMPLDIR)/template.wml
hurd-doc.$(LANGUAGE).html: hurd-doc.wml menu.inc $(TEMPLDIR)/template.wml
hurd-faq.$(LANGUAGE).html: hurd-faq.wml menu.inc $(TEMPLDIR)/template.wml
hurd-install.$(LANGUAGE).html: hurd-install.wml menu.inc $(TEMPLDIR)/template.wml
hurd-links.$(LANGUAGE).html: hurd-links.wml menu.inc $(TEMPLDIR)/template.wml
hurd-news.$(LANGUAGE).html: hurd-news.wml menu.inc $(TEMPLDIR)/template.wml
