#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

#   Arch specific menu entries
<define-menu-item name="hurd">
   [EN:Debian GNU/Hurd:]
   [AR:Debian GNU/Hurd:]
   [DA:Debian GNU/Hurd:]
   [DE:Debian GNU/Hurd:]
   [EL:Debian GNU/Hurd:]
   [EO:Debian GNU/Hurd:]
   [ES:Debian GNU/Hurd:]
   [FI:Debian GNU/Hurd:]
   [FR:Debian GNU/Hurd:]
   [HR:Debian GNU/Hurd:]
   [HU:Debian GNU/Hurd:]
   [IT:Debian GNU/Hurd:]
   [JA:Debian GNU/Hurd:]
   [KO:Debian GNU/Hurd:]
   [NL:Debian GNU/Hurd:]
   [NO:Debian GNU/Hurd:]
   [PL:Debian GNU/Hurd:]
   [PT:Debian GNU/Hurd:]
   [RO:Debian GNU/Hurd:]
   [RU:Debian GNU/Hurd:]
   [SV:Debian GNU/Hurd:]
   [TR:Debian GNU/Hurd:]
   [ZH:Debian GNU/Hurd:]
</define-menu-item>

<define-menu-item name="hurd-cd">
   [EN:Hurd-CDs:]
   [AR:Hurd-CDs:]
   [DA:Hurd på cd:]
   [DE:Hurd-CDs:]
   [EL:Hurd-CDs:]
   [EO:Hurd-CDs:]
   [ES:CDs de Hurd:]
   [FI:Hurd-CDs:]
   [FR:Hurd-CDs:]
   [HR:Hurd-CDs:]
   [HU:Hurd-CDs:]
   [IT:CD di Hurd:]
   [JA:Hurd-CDs:]
   [KO:Hurd-CDs:]
   [NL:Hurd-CDs:]
   [NO:Hurd på cd:]
   [PL:Hurd-CDs:]
   [PT:Hurd-CDs:]
   [RO:Hurd-CDs:]
   [RU:Hurd-CDs:]
   [SV:Hurd på cd:]
   [TR:Hurd-CDs:]
   [ZH:Hurd-CDs:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="hurd"          basename="index">
<menu-item name="news"          basename="hurd-news">
<menu-item name="install"       basename="hurd-install">
<menu-item name="hurd-cd"       basename="hurd-cd">
<menu-item name="doc"           basename="hurd-doc">
<menu-item name="devel"         basename="hurd-devel">
<menu-item name="links"         basename="hurd-links">
<menu-item name="contact"       basename="hurd-contact">

