[ <a href="../">Ports</a> ]

[ <ifneq <get-var WML_SRC_BASENAME> "index"
  "<a href="index">Debian GNU/Hurd</a>"
  "<b>Debian GNU/Hurd</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-news"
  "<a href="hurd-news">News</a>"
  "<b>News</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-install"
  "<a href="hurd-install">Installation</a>"
  "<b>Installation</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-cd"
  "<a href="hurd-cd">Hurd-CDs</a>"
  "<b>Hurd-CDs</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-doc"
  "<a href="hurd-doc">Documentation</a>"
  "<b>Documentation</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-devel"
  "<a href="hurd-devel">Development</a>"
  "<b>Development</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-links"
  "<a href="hurd-links">Links</a>"
  "<b>Links</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "hurd-contact"
  "<a href="hurd-contact">Contact</a>"
  "<b>Contact</b>"
> ]
