#! /usr/bin/perl -w

use strict;

my $infile = $ARGV[0] || "https://packages.debian.org/unstable/main/newpkg";

my $content = `lynx -width=300 -dump $infile`;
my (@packages,@output);

foreach my $line (split "\n",$content) {
#     $line =~ m/^\s*(\*|\d+\. http:)/;
     if ($line =~ m/^\s*\*/) { #) 
	  $line =~ s/^\s*\*\s*//;
	  $line =~ s/\s*\(\d+ days? new\)//;
	  push @packages, $line;
     } elsif ($line =~ m,^\s*(\d+)\. (http://.*),) {
	  my $linkno = $1;
	  my $url = $2;
	  foreach my $l (@packages) {
	       if ($l =~ s/^\[$linkno\]//) {
		    $l =~ s/:/ --/;
                    $l =~ s/ -- / \&mdash; /;
		    push @output, "<li><a href=\"$url\">\\\n\t$l</a></li>";
	       }
	  }
#	  print $line;

     }

}
print "<ul>\n";
print join "\n",@output;
print "\n</ul>\n";
