# This Makefile should need no changes from webwml/english/ports/arm/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/arm
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/arm/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
