#   Translators, do not translate nor copy this file

<!-- BEGIN SECTION -->
<h3><pkg-section main></h3>
<po4a-table>
<!-- DO NOT REMOVE THIS LINE: todo-main -->
</po4a-table>
<!-- END SECTION -->

<!-- BEGIN SECTION -->
<h3><pkg-section contrib></h3>
<po4a-table>
<!-- DO NOT REMOVE THIS LINE: todo-contrib -->
</po4a-table>
<!-- END SECTION -->

<!-- BEGIN SECTION -->
<h3><pkg-section non-free></h3>
<po4a-table>
<!-- DO NOT REMOVE THIS LINE: todo-non-free -->
</po4a-table>
<!-- END SECTION -->
