# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=partners/2016
SUBS=images

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/template.wml \
                        $(ENGLISHSRCDIR)/partners/2016/partners.data \
                        $(ENGLISHSRCDIR)/partners/2016/images/*.gif \
                        $(ENGLISHSRCDIR)/partners/2016/images/*.png \
                        $(ENGLISHSRCDIR)/partners/2016/images/*.jpg 


