# This Makefile should need no changes from
# webwml/english/devel/debian-accessibility/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=devel/debian-accessibility

include $(WMLBASE)/Make.lang

