#   Translators, do not translate nor copy this file

<h3><pkg-section main></h3>
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-main-nostatus -->
<podebconf-table>
<!-- DO NOT REMOVE THIS LINE: todo-main -->
</podebconf-table>
<!-- END SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-main-both -->
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-main-status -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todo-main -->
</podebconf-table-status>
<!-- END SECTION -->

<h3><pkg-section contrib></h3>
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-contrib-nostatus -->
<podebconf-table>
<!-- DO NOT REMOVE THIS LINE: todo-contrib -->
</podebconf-table>
<!-- END SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-contrib-both -->
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-contrib-status -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todo-contrib -->
</podebconf-table-status>
<!-- END SECTION -->

<h3><pkg-section non-free></h3>
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-non-free-nostatus -->
<podebconf-table>
<!-- DO NOT REMOVE THIS LINE: todo-non-free -->
</podebconf-table>
<!-- END SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-non-free-both -->
<!-- BEGIN SECTION -->
<!-- DO NOT REMOVE THIS LINE: todo-non-free-status -->
<podebconf-table-status>
<!-- DO NOT REMOVE THIS LINE: todo-non-free -->
</podebconf-table-status>
<!-- END SECTION -->
