#   Translators, do not translate nor copy this file

<!-- BEGIN SECTION -->
<h3><pkg-section main></h3>
<!-- DO NOT REMOVE THIS LINE: exc-main -->
<!-- END SECTION -->

<!-- BEGIN SECTION -->
<h3><pkg-section contrib></h3>
<!-- DO NOT REMOVE THIS LINE: exc-contrib -->
<!-- END SECTION -->

<!-- BEGIN SECTION -->
<h3><pkg-section non-free></h3>
<!-- DO NOT REMOVE THIS LINE: exc-non-free -->
<!-- END SECTION -->
