# translation-check version="1.2"
<p>Други BTS страници:

<ul>
  <li><a href="./">Начална страница на Системата за Следене на Бъгове.</a>
  <li><a href="Reporting">Инструкции за докладване за бъгове.</a>
  <li><a href="Access">Достъп до журналите на системата за следене на бъгове.</a>
  <li><a href="Developer">Информация за програмисти, отностно системата за следене на бъгове.</a>
  <li><a href="server-control">Информация за програмистите отностно манипулирането на бъгове, използвайте e-mail контролен интерфейс.</a>
  <li><a href="server-refcard">Кратка справочна информация за пощенските сървъри.</a>
  <li><a href="server-request">Подаване на бъг доклади по e-mail.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
