# translation-check version="1.3"
<p>Други страници за системата за следене на грешки:</p>

<ul>
  <li><a href="./">Начална страница на Системата за следене на грешки.</a></li>
  <li><a href="Reporting">Инструкции за докладване на грешки.</a></li>
  <li><a href="Access">Достъп до журналите на системата за следене на грешки.</a></li>
  <li><a href="Developer">Информация за програмисти.</a></li>
  <li><a href="server-control">Управление на доклади за грешки чрез e-mail.</a></li>
  <li><a href="server-refcard">Кратка справочна информация за пощенските сървъри.</a></li>
  <li><a href="server-request">Достъп до доклади за грешки по e-mail.</a></li>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a></li>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a></li>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a></li>
</ul>
