#!/bin/sh

set -e

echo "CVSROOT/addressbook: recreating links"

declare -a dirs
dirs=( "danish" "french" "german" "italian" "japanese" "spanish" )
[ -d webwml/english/Pics ] || { echo No directory webwml/english/Pics ; exit 1 ; }
cd webwml
for dir in $dirs; do
	if [ -d $dir ]; then
		cd $dir
		if [ ! -L Pics ]; then
			ln -s ../english/Pics ;
		fi
		cd .. ;
	fi ;
done

echo "CVSROOT/addressbook: done"
