# Considering webwml/english/partners/images/* shouldn't be in translations,
# there should be no need to copy this file to translation directories.

WMLBASE=../..
CUR_DIR=partners/images
SUBS=

include $(WMLBASE)/Make.lang
