# This Makefile should need no changes from the equivalent makefile under
# the english/ directory.
# Please send a message to debian-cd if you need to modify anything,
# so the problem can be fixed.

top_dir := ..
cur_dir := 
sub_dirs := 

include $(dir $(top_dir))/Make.lang
