# This Makefile should need no changes from webwml/english/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../../..
CUR_DIR=international/spanish/contrib/apt-guia-usuarios.html
SUBS=

include $(WMLBASE)/Make.lang


install::
	install -m 664 -p *.html $(HTMLDIR)


cleandest::
	rm -f $(HTMLDIR)/*.html
