# This Makefile should need no changes from webwml/english/ports/arm/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/arm
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml menu.inc $(TEMPLDIR)/template.wml
softwaremap.$(LANGUAGE).html: softwaremap.wml menu.inc $(TEMPLDIR)/template.wml
