#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="arm">
   [EN:Debian for ARM:]
   [AR:Debian for ARM:]
   [DA:Debian til ARM:]
   [DE:Debian für ARM:]
   [EL:Debian for ARM:]
   [EO:Debian for ARM:]
   [ES:Debian para ARM:]
   [FI:Debian for ARM:]
   [FR:Debian for ARM:]
   [HR:Debian for ARM:]
   [HU:Debian for ARM:]
   [IT:Debian per ARM:]
   [JA:Debian for ARM:]
   [KO:Debian for ARM:]
   [NL:Debian for ARM:]
   [NO:Debian for ARM:]
   [PL:Debian for ARM:]
   [PT:Debian para ARM:]
   [RO:Debian for ARM:]
   [RU:Debian for ARM:]
   [SV:Debian för ARM:]
   [TR:Debian for ARM:]
   [ZH:Debian for ARM:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="arm"           basename="index">
<menu-item name="news"          basename="news">
<menu-item name="status"        basename="status">
<menu-item name="links"         basename="links">
<menu-item name="softwaremap"   basename="softwaremap">

