#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"


<define-menu-item name="arm">
  <gettext domain="ports">Debian for ARM</gettext>
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="arm"           basename="index">
<menu-item name="news"          basename="news">
<menu-item name="status"        basename="status">
<menu-item name="links"         basename="links">
<menu-item name="softwaremap"   basename="softwaremap">

