#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="m68k">
   [EN:Debian for Motorola 680x0:]
   [AR:Debian for Motorola 680x0:]
   [DA:Debian for Motorola 680x0:]
   [DE:Debian für Motorola 680x0:]
   [EL:Debian for Motorola 680x0:]
   [EO:Debian for Motorola 680x0:]
   [ES:Debian para Motorola 680x0:]
   [FI:Debian for Motorola 680x0:]
   [FR:Debian pour Motorola 680x0:]
   [HR:Debian for Motorola 680x0:]
   [HU:Debian for Motorola 680x0:]
   [IT:Debian per Motorola 680x0:]
   [JA:Debian for Motorola 680x0:]
   [KO:Debian for Motorola 680x0:]
   [NL:Debian for Motorola 680x0:]
   [NO:Debian for Motorola 680x0:]
   [PL:Debian for Motorola 680x0:]
   [PT:Debian para Motorola 680x0:]
   [RO:Debian for Motorola 680x0:]
   [RU:Debian for Motorola 680x0:]
   [SV:Debian för Motorola 680x0:]
   [TR:Debian for Motorola 680x0:]
   [ZH:Debian for Motorola 680x0:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="m68k"          basename="index">
<menu-item name="links"         basename="links">

