# This Makefile should need no changes from webwml/english/security/key-rollover/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=security/key-rollover
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml
	$(WML) $(<F)
