# This Makefile should need no changes from webwml/english/legal/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=legal
SUBS=licenses

include $(WMLBASE)/Make.lang

