# This Makefile should need no changes from webwml/english/releases/potato/installguide/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../..
CUR_DIR=releases/potato/installguide
SUBS=

include $(WMLBASE)/Make.lang
