#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Смесь&nbsp;Debian&nbsp;Hamradio</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">О&nbsp;смеси</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Архив&nbsp;новостей</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Свяжитесь&nbsp;с&nbsp;нами</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Получить&nbsp;смесь</a>y
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Загрузить&nbsp;<q>живые</q>&nbsp;образы</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Использование&nbsp;метапакетов</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Документация</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Руководство&nbsp;Debian&nbsp;Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Поддержка</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Разработка</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Команда&nbsp;сопровождающих&nbsp;Hamradio</a></li>
        <li><a href="<hamradio-maintguide/>">Руководство&nbsp;сопровождающих&nbsp;Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Забавное</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
