# This Makefile should need no changes from webwml/english/international/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=international/German
SUBS=

include $(WMLBASE)/Make.lang


credits_website.$(LANGUAGE).html: credits_website.wml $(ENGLISHSRCDIR)/../german/international/German/credits.tags
