# This Makefile should need no changes from webwml/english/releases/sarge/debian-installer/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../..
CUR_DIR=releases/sarge/debian-installer
SUBS=

include $(WMLBASE)/Make.lang
