#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/gis/">Смесь&nbsp;Debian&nbsp;GIS</a></p>
    <ul>
      <li><a href="$(HOME)/blends/gis/about">О&nbsp;смеси</a></li>
      <li><a href="$(HOME)/blends/gis/contact">Свяжитесь&nbsp;с&nbsp;нами</a></li>
      <li><a href="$(HOME)/blends/gis/get/">Получить&nbsp;смесь</a>y
         <ul>
         <li><a href="$(HOME)/blends/gis/get/live">Загрузить&nbsp;<q>живые</q>&nbsp;образы</a></li>
         <li><a href="$(HOME)/blends/gis/get/metapackages">Использование&nbsp;метапакетов</a></li>
	 </ul>
      </li>
        <ul>
        <li><a href="<gis-policy-html/>">Debian&nbsp;GIS</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/gis/support">Поддержка</a></li>
      <li><a href="$(HOME)/blends/gis/deriv">Производные</a>
      <li><a href="$(HOME)/blends/gis/dev">Разработка</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianGis">Команда&nbsp;сопровождающих&nbsp;GIS</a></li>
        <li><a href="<gis-policy-html/>">Руководство&nbsp;сопровождающих&nbsp;GIS</a></li>
        </ul>
      </li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
