# This Makefile should need no changes from webwml/english/ports/powerpc/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/powerpc
SUBS=inst

include $(WMLBASE)/Make.lang

