#use wml::debian::submenu
#use wml::debian::common_tags
#include "$(ENGLISHDIR)/ports/menu.defs"
#use wml::debian::translation-check translation="1.14"

<bind-gettext-domain domain="ports" />

<define-menu-item name="laptops">
  <gettext domain="ports">Debian за лаптопи</gettext>
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="laptops"       basename="index">

