#!/soft/eleves/i386/bin/bash
source="/home/mquinson/CVSIMPORT/l10n/english/international/l10n"
cible="/home/mquinson/debian/webwml/english/international/l10n"

cd $cible;
for name in `ls $source` ; do
	rm -f $name;
	ln -s $source/$name $name;
done;

source="/home/mquinson/CVSIMPORT/l10n/french/international/l10n"
cible="/home/mquinson/debian/webwml/french/international/l10n"

cd $cible;
for name in `ls $source` ; do
	rm -f $name;
	ln -s $source/$name $name;
done;
