<p>Andra sidor i felrapporteringssystemet:

<ul>
  <li><A href="./">Framsida för felrapporteringssystemet.</A>
  <li><A href="Reporting">Instruktioner om hur man rapporterar fel.</A>
  <li><A href="Access">Komma åt loggarna på andra sätt än via webben.</A>
  <li><A href="Developer">Utvecklarinformation om hur systemet används.</A>
  <li><A href="server-control">Utvecklarinformation om hur felrapporter kan
      manipuleras per e-post.</A>
  <li><A href="server-refcard">E-postserverns referenskort.</A>
  <li><A href="server-request">Begära felrapporter per e-post.</A>
# <li><A href="db/ix/full.html">En komplett lista över ej åtgärdade och
#     nyligen inkomna felrapporter.</A>
# <li><A href="db/ix/packages.html">Paket med felrapporter.</A>
# <li><A href="db/ix/maintainers.html">Ansvariga för paket för vilka det
#     finns felrapporter.</A>
</ul>
