#use wml::debian::blends::gis
#use wml::debian::translation-check translation="1.4"

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/gis/">Debian&nbsp;GIS&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/gis/about">Om</a></li>
      <li><a href="$(HOME)/blends/gis/contact">Kontakt</a></li>
      <li><a href="$(HOME)/blends/gis/get/">Få&nbsp;fat&nbsp;i&nbsp;blend'en</a>
         <ul>
         <li><a href="$(HOME)/blends/gis/get/live">Download&nbsp;liveaftryk</a></li>
         <li><a href="$(HOME)/blends/gis/get/metapackages">Anvend&nbsp;metapakkerne</a></li>
         </ul>
      </li>
      <li><a href="$(HOME)/blends/gis/support">Support</a></li>
      <li><a href="$(HOME)/blends/gis/deriv">Derivativer</a></li>
      <li><a href="https://wiki.debian.org/DebianGIS#Development">Udvikling</a>
        <ul>
        <li><a href="<gis-policy-html/>">GIS Team Policy</a></li>
        </ul>
      </li>
      <li><a href="https://twitter.com/DebianGIS"><img src="$(HOME)/blends/gis/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
