# This Makefile should need no changes from webwml/english/ports/alpha/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=..
CUR_DIR=ports
SUBS=alpha arm sparc sparc64 powerpc

include $(WMLBASE)/Make.lang

