#!/bin/sh
# this script is run each day from ~tbm's crontab.
# 51 23 * * * /org/nm.debian.org/cronjobs/dump_db
set -e

TIME=`date +%Y-%m-%d`

umask 002
cd /org/nm.debian.org/backup

pg_dump newmaint > newmaint_$TIME
bzip2 newmaint_$TIME

pg_dump gpg-coord > gpg-coord_$TIME
bzip2 gpg-coord_$TIME

