#!/bin/sh
# this script is run each week from ~tbm's crontab.
# 2 15 * * wed /org/nm.debian.org/cronjobs/gpg_weekly
set -e

umask 002
cd /org/nm.debian.org/bin

# Inform people who have no place entries
./gpg_no_places

