#!/bin/sh
# this script is run each hour from ~tbm's crontab.
# 21 * * * * /org/nm.debian.org/cronjobs/wml-build
set -e

umask 002
cd /org/nm.debian.org/wml/webwml
cvs -Q update

cd /org/nm.debian.org/wml/newmaint
cvs -Q update
make > /dev/null
make install > /dev/null

