# This Makefile should need no changes from webwml/english/ports/powerpc/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../../..
CUR_DIR=ports/powerpc/inst
SUBS=

include $(WMLBASE)/Make.lang

apus.$(LANGUAGE).html: apus.wml menu.inc $(TEMPLDIR)/template.wml
booting.$(LANGUAGE).html: booting.wml menu.inc $(TEMPLDIR)/template.wml
chrp.$(LANGUAGE).html: chrp.wml menu.inc $(TEMPLDIR)/template.wml
install.$(LANGUAGE).html: install.wml menu.inc $(TEMPLDIR)/template.wml
mbx.$(LANGUAGE).html: mbx.wml menu.inc $(TEMPLDIR)/template.wml
pmac.$(LANGUAGE).html: pmac.wml menu.inc $(TEMPLDIR)/template.wml
prep.$(LANGUAGE).html: prep.wml menu.inc $(TEMPLDIR)/template.wml
rs6k.$(LANGUAGE).html: rs6k.wml menu.inc $(TEMPLDIR)/template.wml
