#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

<define-menu-item name="powerpc">
   [AR:Debian for PowerPC:]
   [DA:Debian for PowerPC:]
   [DE:Debian für PowerPC:]
   [EL:Debian for PowerPC:]
   [EN:Debian for PowerPC:]
   [EO:Debian for PowerPC:]
   [ES:Debian para PowerPC:]
   [FI:Debian for PowerPC:]
   [FR:Debian for PowerPC:]
   [HR:Debian for PowerPC:]
   [HU:Debian for PowerPC:]
   [JA:Debian for PowerPC:]
   [KO:Debian for PowerPC:]
   [NL:Debian for PowerPC:]
   [NO:Debian for PowerPC:]
   [PL:Debian for PowerPC:]
   [PT:Debian for PowerPC:]
   [RO:Debian for PowerPC:]
   [RU:Debian for PowerPC:]
   [SV:Debian för PowerPC:]
   [TR:Debian for PowerPC:]
   [ZH:Debian for PowerPC:]
</define-menu-item>

<menu-item name="ports"         basename="../../index">
<menu-item name="powerpc"       basename="../index">
<menu-item name="devel"         basename="../devel">
<menu-item name="doc"           basename="../docu">
<menu-item name="install"       basename="install">

