#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

<define-menu-item name="powerpc">
  <gettext domain="ports">Debian for PowerPC</gettext>
</define-menu-item>

<menu-item name="ports"         basename="../../index">
<menu-item name="powerpc"       basename="../index">
<menu-item name="devel"         basename="../devel">
<menu-item name="doc"           basename="../docu">
<menu-item name="install"       basename="install">

