# This Makefile should need no changes from webwml/chinese/international/chinese/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=international/chinese
SUBS=devel doc faq News screenshot
ZHTEMPLATE=$(WMLBASE)/template/debian-zh/template.tmpl

include $(WMLBASE)/Make.lang


index.zh-cn.html index.zh-tw.html: index.wml News/index.wml