# This Makefile should need no changes from webwml/english/misc/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=misc
SUBS=

include $(WMLBASE)/Make.lang


merchandise.$(LANGUAGE).html: ../../english/misc/merchandise.data \
		../../english/misc/merchandise.def
