#!/bin/bash

# see README for more information

umask 002
. /org/www.debian.org/cron/common.sh

# locking
if lockfile -! -l 43200 -r 0 "$crondir/lessoften.lock"; then
  echo `hostname` is unable to start update, lock file exists.
  exit 1
fi
trap "rm -f $crondir/lessoften.lock" exit

# rotate the previous log file
savelog $crondir/lessoften.log &> /dev/null

echo "starting the lessoften cron job at `date`" > $crondir/lessoften.log

echo "creating mailing-lists.txt..." >> $crondir/lessoften.log
make -s -C $webtopdir/webwml/english/MailingLists mailing-lists.txt
install -m 664 -g debwww \
  $webtopdir/webwml/english/MailingLists/mailing-lists.txt \
  $webdir/misc/mailing-lists.txt

echo "copying events/materials/ in place..." >> $crondir/lessoften.log
install -d -m 2775 -g debwww $webdir/events/materials
cp -a $webtopdir/events-materials/* $webdir/events/materials/

#echo "rebuilding the potato release docs..." >> $crondir/lessoften.log
#$webtopdir/bf/potato/cvsbuild >> $crondir/lessoften.log
#echo "copying potato release docs in place..." >> $crondir/lessoften.log
## -f because of symlinks
#cp -af $webtopdir/bf/potato/boot-floppies/documentation/arch/* $webdir/releases/potato/

echo "rebuilding the woody release docs..." >> $crondir/lessoften.log
$webtopdir/bf/woody/cvsbuild >> $crondir/lessoften.log
echo "copying woody release docs in place..." >> $crondir/lessoften.log
# -f because of symlinks
cp -af $webtopdir/bf/woody/boot-floppies/documentation/arch/* $webdir/releases/woody/

# the below scripts will echo what they are doing themselves
$crondir/people_scripts/update.packages+sources >> $crondir/lessoften.log
$crondir/people_scripts/update.people.html >> $crondir/lessoften.log

# previously in parts/1l10ndata, from bouz
cd $crondir/datafiles/
echo "updating the database file used to display l10n stats..." >> $crondir/lessoften.log
wget -q -N http://ftp-master.debian.org/~barbier/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on ftp-master!"; exit 1; }
gunzip -c -f unstable.gz > unstable.ftp-master
ln -sf $crondir/datafiles/unstable.ftp-master $webtopdir/webwml/english/international/l10n/data/unstable.ftp-master

echo "updating the non-US database file used to display l10n stats..." >> $crondir/lessoften.log
wget -q -N http://non-us.debian.org/~barbier/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on non-us!"; exit 1; }
gunzip -c -f unstable.gz > unstable.non-US
ln -sf $crondir/datafiles/unstable.non-US $webtopdir/webwml/english/international/l10n/data/unstable.non-US

# cleanup
rm -f unstable.gz

echo "extracting the list of languages..." >> $crondir/lessoften.log
cd $webtopdir/webwml/english/international/l10n
./scripts/list-languages.pl data/unstable.ftp-master data/unstable.non-US > data/langs

echo " ** lessoften cron job done *** " >> $crondir/lessoften.log
