#!/bin/bash -e

# see README for more information

umask 002
. /org/www.debian.org/cron/common.sh

# locking
if lockfile -! -l 43200 -r 0 "$crondir/often.lock"; then
  echo `hostname` is unable to start update, lock file exists.
  exit 1
fi
trap "rm -f $crondir/often.lock" exit

# rotate the previous log file
savelog -g debwww -m 664 $crondir/log/often.log > /dev/null

# making the time of job start explicit
date > $crondir/log/often.log

export CVS_RSH=ssh
cd $crondir
cvs update -d -P 2>&1 | tee -a $crondir/log/often.log >/dev/null

cd parts
run-parts --verbose $crondir/parts >> $crondir/log/often.log 2>&1

echo " *** the often cron job is done *** " >> $crondir/log/often.log

# making the time of job stop explicit
date >> $crondir/log/often.log
