# This Makefile should need no changes from webwml/english/ports/sparc/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/sparc
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml menu.inc $(TEMPLDIR)/template.wml
credits.$(LANGUAGE).html: credits.wml menu.inc $(TEMPLDIR)/template.wml
porting.$(LANGUAGE).html: porting.wml menu.inc $(TEMPLDIR)/template.wml
problems.$(LANGUAGE).html: problems.wml menu.inc $(TEMPLDIR)/template.wml
