[ <a href="../">Ports</a> ]

[ <ifneq <get-var WML_SRC_BASENAME> "index"
  "<a href="index">Debian SPARC</a>"
  "<b>Debian SPARC</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "credits"
  "<a href="credits">Credits</a>"
  "<b>Credits</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "porting"
  "<a href="porting">Documentation</a>"
  "<b>Documentation</b>"
> ]

[ <ifneq <get-var WML_SRC_BASENAME> "problems"
  "<a href="problems">Problems</a>"
  "<b>Problems</b>"
> ]
