#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="sparc">
   [EN:Debian for Sparc:]
   [AR:Debian for Sparc:]
   [DA:Debian til Sparc:]
   [DE:Debian für Sparc:]
   [EL:Debian for Sparc:]
   [EO:Debian for Sparc:]
   [ES:Debian para Sparc:]
   [FI:Debian for Sparc:]
   [FR:Debian pour Sparc:]
   [HR:Debian za Sparc:]
   [HU:Debian for Sparc:]
   [IT:Debian per Sparc:]
   [JA:Debian for Sparc:]
   [KO:Debian for Sparc:]
   [NL:Debian for Sparc:]
   [NO:Debian for Sparc:]
   [PL:Debian for Sparc:]
   [PT:Debian para Sparc:]
   [RO:Debian for Sparc:]
   [RU:Debian for Sparc:]
   [SV:Debian för Sparc:]
   [TR:Debian for Sparc:]
   [ZH:Debian for Sparc:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="sparc"         basename="index">
<menu-item name="credits"       basename="credits">
<menu-item name="porting"       basename="porting">
<menu-item name="problems"      basename="problems">

