# This Makefile should need no change from webwml/english/ports/ia64/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/ia64
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
