<p>Andre sider i fejlrapporteringssystemet:</p>

<ul>
  <li><a href="./">Hovedsiden for fejlrapporteringssystemet.</a></li>
  <li><a href="Reporting">Hvordan man rapporterer en fejl.</a></li>
  <li><a href="Access">Hvordan man tilgår fejlloggene.</a></li>
  <li><a href="Developer">Oplysninger til udviklere om fejlrapporteringssystemet.</a></li>
  <li><a href="server-control">Oplysninger til udviklere om håndtering af fejl via e-mail.</a></li>
  <li><a href="server-refcard">Postservernes referencekort.</a></li>
  <li><a href="server-request">Få tilsendt fejlrapporter via e-mail.</a></li>
#  <li><a href="db/ix/full.html">Komplet liste over alle ikke-løste og nye fejlrapporter</a></li>
#  <li><a href="db/ix/packages.html">Pakker med fejlrapporter.</a></li>
#  <li><a href="db/ix/maintainers.html">Vedligeholderes pakker med fejlrapporter.</a></li>
</ul>
