# If this makefile is not generic enough to support a translation,
# please contact debian-www.

# random hint: for i in ../../english/Pics/*.png ../../english/Pics/debian.jpg ../../english/Pics/logo-50.jpg; do ln -s $i . ; done

WMLBASE=../../../
CUR_DIR=women/profiles/pictures
SUBS=

include $(WMLBASE)/Make.lang
