<p>BTS:n muut sivut:</p>

<ul>
  <li><a href="./">Debianin vianseurantajärjestelmän pääsivu</a></li>
  <li><a href="Reporting">Ohjeita vioista ilmoittamiseen</a></li>
  <li><a href="Access">Vianseurantalogien hakeminen</a></li>
  <li><a href="Developer">Järjestelmän käyttöohjeita kehittäjille</a></li>
  <li><a href="server-control">Tietoa vikailmoitusten käsittelystä
    sähköpostitse kehittäjille</a></li>
  <li><a href="server-refcard">Postipalvelimen pikaopas</a></li>
  <li><a href="server-request">Vikailmoitusten kyseleminen
    sähköpostitse</a></li>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#    reports.</a></li>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a></li>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#    reports.</a></li>
</ul>
