<p>BTS:n muut sivut:

<ul>
  <li><a href="./">Debianin vianseurantajärjestelmän pääsivu</a>
  <li><a href="Reporting">Ohjeita vioista ilmoittamiseen</a>
  <li><a href="Access">Vianseurantalogien hakeminen muutoin kuin www:n kautta</a>
  <li><a href="Developer">Järjestelmän käyttöohjeita kehittäjille</a>
  <li><a href="server-control">Tietoa vikailmoitusten käsittelystä sähköpostitse kehittäjille</a>
  <li><a href="server-refcard">Postipalvelimen pikaopaskirjanen</a>
  <li><a href="server-request">Vikailmoitusten kyseleminen sähköpostitse</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
