  <small>
  <ul>
  <li>Liput:
  <input type="radio" name="archive" value="no" checked> aktiivinen vika
  <input type="radio" name="archive" value="yes"> arkistoitu vika
  <input type="checkbox" name="raw" value="yes">Ei j‰rjestyst‰ tilan/vakavuuden perusteella
  <li>K‰‰nteinen j‰rjestys:
  <input type="checkbox" name="sev-rev" value="yes">tila
  <input type="checkbox" name="pend-rev" value="yes">vakavuus
  <input type="checkbox" name="bug-rev" value="yes">vika
  <li>Sis‰llyt‰ tilat:
  <input type="checkbox" name="pend-inc" value="pending">Avoin
  <input type="checkbox" name="pend-inc" value="forwarded">Siirretty eteenp‰in
  <input type="checkbox" name="pend-inc" value="pending-fixed">Ratkaisematon
  <input type="checkbox" name="pend-inc" value="fixed">Korjattu
  <input type="checkbox" name="pend-exc" value="done">Tehty
  <li>Poista tilat:
  <input type="checkbox" name="pend-exc" value="pending">Avoin
  <input type="checkbox" name="pend-exc" value="forwarded">Siirretty eteenp‰in
  <input type="checkbox" name="pend-exc" value="pending-fixed">Ratkaisematon
  <input type="checkbox" name="pend-exc" value="fixed">Korjattu
  <input type="checkbox" name="pend-exc" value="done">Tehty
  <li>Vakavuudet, jotka sis‰llytet‰‰n:
  <input type="checkbox" name="sev-inc" value="critical">Critical
  <input type="checkbox" name="sev-inc" value="grave">Grave
  <input type="checkbox" name="sev-inc" value="serious">Serious
  <input type="checkbox" name="sev-inc" value="important">Important
  <input type="checkbox" name="sev-inc" value="normal">Normal
  <input type="checkbox" name="sev-inc" value="minor">Minor
  <input type="checkbox" name="sev-inc" value="wishlist">Wishlist
  <input type="checkbox" name="sev-inc" value="fixed">Fixed
  <li>Vakavuudet, jotka poistetaan:
  <input type="checkbox" name="sev-exc" value="critical">Critical
  <input type="checkbox" name="sev-exc" value="grave">Grave
  <input type="checkbox" name="sev-exc" value="serious">Serious
  <input type="checkbox" name="sev-exc" value="important">Important
  <input type="checkbox" name="sev-exc" value="normal">Normal
  <input type="checkbox" name="sev-exc" value="minor">Minor
  <input type="checkbox" name="sev-exc" value="wishlist">Wishlist
  <input type="checkbox" name="sev-exc" value="fixed">Fixed
  </ul>
  </small>
