#use wml::debian::blends::hamradio
#use wml::debian::translation-check translation="1.1"

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Debian&nbsp;Hamradio&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">Om</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Nyhedsarkiv</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Kontakt</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Få&nbsp;fat&nbsp;i&nbsp;blend'en</a>
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Download&nbsp;liveaftryk</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Anvend&nbsp;metapakkerne</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Dokumentation</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Debian&nbsp;Hamradio&nbsp;Handbook</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Support</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Udvikling</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Hamradio Maintainers Team</a></li>
        <li><a href="<hamradio-maintguide-html/>">Hamradio Maintainers Guide</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Sjov</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/blends/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
