<p>その他の BTS ページ:

<ul>
  <li><a href="./">バグ追跡システムメインページ</a>
  <li><a href="Reporting">バグ報告の勧め(使用説明書)</a>
  <li><a href="Access">WWW 以外でバグ報告のログを参照する方法</a>
  <li><a href="Developer">バグ追跡システムの使用方法に関する開発者情報</a>
  <li><a href="server-control">電子メールでバグ報告を操作することに関する
      開発者情報</a>
  <li><a href="server-refcard">メールサーバリファレンスカード</a>
  <li><a href="server-request">電子メールによるバグ報告の取り寄せ</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
