<p>그 외의 페이지:

<ul>
  <li><a href="./">버그 추적 시스템 메인 차례 페이지.</a>
  <li><a href="Reporting">버그를 보고하는 방법.</a>
  <li><a href="Access">웹 이외에 버그 추적 기록을 접근하는 방법.</a>
  <li><a href="Developer">버그 처리 시스템에 관한 개발자 정보.</a>
  <li><a href="server-control">개발자 정보 - 이메일로 컨트롤하는 버그 처리.</a>
  <li><a href="server-refcard">메일서버의 참고 카드.</a>
  <li><a href="server-request">요청 메일서버의 문서.</a>
#  <li><a href="db/ix/full.html">미해결 상태 혹은 최근에 해결된 버그 보고의 전체 리스트.</a>
#  <li><a href="db/ix/packages.html">버그 보고가 있는 패키지.</a>
#  <li><a href="db/ix/maintainers.html">버그 보고가 있는 패키지의 관리자.</a>
</ul>
