# This Makefile should need no changes from
# webwml/english/releases/potato/Makefile, so we can just include the
# English version here.
#
# If something in it needs modification, send a message to debian-www
# so the problem can be fixed.

include ../../../english/releases/potato/Makefile
