# This Makefile should need no change from webwml/english/ports/hppa/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/hppa
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/hppa/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
