#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="hppa">
   [EN:Debian for PA-RISC:]
   [AR:Debian for PA-RISC:]
   [DA:Debian til PA-RISC:]
   [DE:Debian für PA-RISC:]
   [EL:Debian for PA-RISC:]
   [EO:Debian for PA-RISC:]
   [ES:Debian para PA-RISC:]
   [FI:Debian for PA-RISC:]
   [FR:Debian pour PA-RISC:]
   [HR:Debian for PA-RISC:]
   [HU:Debian for PA-RISC:]
   [IT:Debian per PA-RISC:]
   [JA:Debian for PA-RISC:]
   [KO:Debian for PA-RISC:]
   [NL:Debian for PA-RISC:]
   [NO:Debian for PA-RISC:]
   [PL:Debian for PA-RISC:]
   [PT:Debian para PA-RISC:]
   [RO:Debian for PA-RISC:]
   [RU:Debian for PA-RISC:]
   [SV:Debian för PA-RISC:]
   [TR:Debian for PA-RISC:]
   [ZH:Debian for PA-RISC:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="hppa"          basename="index">
<menu-item name="news"          basename="news">
<menu-item name="systems"       basename="systems">

