# This Makefile should need no changes from
# the file webwml/english/devel/debian-installer/Makefile
# because webwml/english/devel/debian-installer/Makefile is "upstream"
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=devel/debian-installer
YEARS:=$(wildcard News/[12][0-9][0-9][0-9])
SUBS=$(YEARS)

include $(WMLBASE)/Make.lang

# last line
