# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=..
CUR_DIR=download
SUBS=

GETTEXTFILES += download.mo

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml \
  $(TEMPLDIR)/release_info.wml \
  $(TEMPLDIR)/release_images.wml \

