# This Makefile should need no changes from webwml/english/ports/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=ports
# list any subdirectories in the following variable. Any directories listed
# must exist or the make will not work
SUBS=alpha beowulf laptops mips powerpc sparc sparc64

include $(WMLBASE)/Make.lang
include $(WMLBASE)/Make.common

include $(WMLBASE)/Make.dep.templ    
include $(WMLBASE)/Make.dep.generic
