# This Makefile should need no change from webwml/english/ports/parisc/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/parisc
SUBS=

include $(WMLBASE)/Make.lang

