<!--translation 1.1-->

<p>Otras páginas del Sistema de seguimiento de fallos (BTS en 
inglés):

<ul>
  <li><a href="./">Página de contenidos principal del Sistema de
       seguimiento de fallos de Debian.</a>
  <li><a href="Reporting">Instrucciones de cómo informar de un 
fallo.</a>
  <li><a href="Access">Otras formas de acceder a los registros de seguimiento
       de fallos que no sean por WWW.</a>
  <li><a href="Developer">Información para desarrolladores sobre
       cómo utilizar el sistema.</a>
  <li><a href="server-control">Información para desarrolladores sobre
       cómo manipular fallos utilizando el interfaz de correo
       electrónico.</a>
  <li><a href="server-refcard">Tarjeta de referencia del servidor de 
correo.</a>
  <li><a href="server-request">Cómo pedir informes de error por 
correo.</a>
#  <li><a href="db/ix/full.html">Lista completa de informes de errores
#       pendientes y recientes.</a>
#  <li><a href="db/ix/packages.html">Paquetes con informes de error.</a>
#  <li><a href="db/ix/maintainers.html">Mantenedores de paquetes con informes 
#
#de error.</a>
</ul>

