# This Makefile should need no changes from webwml/english/CD/http-ftp/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=CD/http-ftp
SUBS=

include $(WMLBASE)/Make.lang

