#!/usr/bin/perl
#
# Count the number of Debian consultants
#
# Written by: Behan Webster <behanw@pobox.com>
#

$filename	= 'consultant.data';
$comment	= '^#\s*Consultant:\s*(.*)\s*$';

# Read in file
open( FILE, "<$filename" ) || die "$filename: $!\n";

my $buffer = "";
my $outfile = "consultant.inc";
my $count = 0;
my %country;
my $list ='';

# Count consultants/countries
while ( <FILE> ) {
	chomp;
	if( /$comment/ ) {
		$count++;
		$country{$1}++;
	}
}
@_ = keys %country;

my $number = $#_ + 1;

close( FILE );

# Print results

foreach ( sort keys %country ) {
	printf "%-4d  %s\n", $country{$_}, $_;
	$buffer .= sprintf ("<define-tag %s_count>%d</define-tag>\n", $_, $country{$_});
	$list .= "$_-$country{$_} ";
}

# Report numbers and update file in buffer
print "Number of consultants: $count\n";
print "Number of countries:   $number\n";
$buffer .= sprintf ("<define-tag total_consultant>%d</define-tag>\n", $count);
$buffer .= sprintf ("<define-tag total_country>%d</define-tag>\n", $number);
$buffer .= sprintf ("<define-tag list_country>%s</define-tag>\n", $list);

open (FILE, ">$outfile") || die "$outfile: $!\n";
print FILE $buffer;
close (FILE);
