#!/bin/sh -e

# this script fetches some stuff from the FTP stuff that's needed
# and puts it in /org/www.debian.org/cron/ftpfiles

. `dirname $0`/../common.sh

[ -d $crondir/ftpfiles ] || mkdir -p $crondir/ftpfiles
cd $crondir/ftpfiles
ftpsite=ftp.de.debian.org

# needed for WNPP, webwml/english/devel/wnpp/wnpp.pl
wget -q -N http://${ftpsite}/debian/indices/Maintainers
ln -sf $crondir/ftpfiles/Maintainers $webtopdir/webwml/english/devel/wnpp/Maintainers

# needed for 7doc_updates
# this is FTP because otherwise we get all those ugly HTML thingies
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/doc/
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/e/emacsen-common/emacsen-common_*.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/b/build-essential/build-essential_*_i386.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/d/dpkg/dpkg-doc_*.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/m/menu/menu_*_i386.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/j/java-common/java-common_*.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/d/debian-policy/debian-policy_*.deb
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/p/python-defaults/python_*.deb

# installation guide
wget -q -r -N -nH --cut-dirs=1 ftp://${ftpsite}/debian/pool/main/i/installation-guide/installation-guide_*

echo
