#!/bin/sh -e

# this file updates the lists.cfg file from list admins' directory
# so that webwml/english/MailingLists/{,un}subscribe.wml can use it

. `dirname $0`/../common.sh

cd $crondir/datafiles/
# Joey has the canonical version symlinked here:
wget -q -N http://murphy.debian.org/lists.cfg || { echo "couldn't fetch a new lists.cfg!"; exit 1; }

# the appropriate Makefile will do the rest of the work
ln -sf $crondir/datafiles/lists.cfg $webtopdir/webwml/english/MailingLists/lists.cfg

echo
