#!/bin/sh -e

# this file updates pseudo-packages.* files from the canonical location
# so that webwml/english/Bugs/pseudo-packages.wml can use it

. `dirname $0`/../common.sh

# James has the canonical version symlinked here:
# this ftp-master rsyncd module stopped working after ries crash 2007-10
# but isn't really necessary, cf. bug#449097
rsync -upL ftp-master::masterfiles/pseudo-packages.description $crondir/datafiles

# this will start working at 2007-12-02 6:25 local rietz time :)
#wget http://bugs.debian.org/pseudo-packages.description -O $crondir/datafiles/pseudo-packages.description

# the appropriate Makefile will do the rest of the work
ln -sf $crondir/datafiles/pseudo-packages.description \
 $webtopdir/webwml/english/Bugs/pseudo-packages.description

echo
