#!/bin/sh -e

# this file updates pseudo-packages.* files from the canonical location
# so that webwml/english/Bugs/pseudo-packages.wml can use it

. `dirname $0`/../common.sh

# use the BTS' copy -joy, 2007-12-03
wget -q http://bugs.debian.org/pseudopackages/pseudo-packages.description \
     -O $crondir/datafiles/pseudo-packages.description.new

if [ -s $crondir/datafiles/pseudo-packages.description.new ]; then
  mv $crondir/datafiles/pseudo-packages.description.new \
     $crondir/datafiles/pseudo-packages.description
fi

# the appropriate Makefile will do the rest of the work
ln -sf $crondir/datafiles/pseudo-packages.description \
       $webtopdir/webwml/english/Bugs/pseudo-packages.description

echo
