#!/bin/sh -e

# this file updates pseudo-packages.* files from FTP admins' directory
# so that webwml/english/Bugs/pseudo-packages.wml can use it

. `dirname $0`/../common.sh

# James has the canonical version symlinked here:
rsync -upL auric::masterfiles/pseudo-packages.description $crondir/datafiles

# the appropriate Makefile will do the rest of the work
ln -sf $crondir/datafiles/pseudo-packages.description \
 $webtopdir/webwml/english/Bugs/pseudo-packages.description

echo
