#!/bin/sh

# update the webwml repository from CVS

. `dirname $0`/../common.sh

cd $webtopdir/webwml

umask 002

CVS_RSH=ssh
export CVS_RSH

time cvs update -d -P &> $crondir/log/cvs_update.log

echo
