#!/bin/sh

# run make on all the language directories

. `dirname $0`/../common.sh

cd $webtopdir/webwml

umask 002

savelog -g debwww -m 664 $crondir/log/wml_run.log >/dev/null

time make install &> $crondir/log/wml_run.log

test -d $webdir/mirror/timestamps || mkdir -p -m 2775 -g debwww $webdir/mirror/timestamps
date -u > $webdir/mirror/timestamps/www-master.debian.org

echo
