#!/bin/sh -e

# this script re-creates README.mirrors.html, README.non-US.html and
# mirrors_full.html files in case Mirrors.masterlist was modified
# (updated from CVS in 4webwml)

# however, the following is all obsolete because it's been converted into
# list(|-full|-non-US).wml so it's built by make -joy, 2007-11-02

. `dirname $0`/../common.sh

prog=$webtopdir/webwml/english/mirror/mirror_list.pl
masterlist=$webtopdir/webwml/english/mirror/Mirrors.masterlist

#if [ ! -f $webdir/mirror/list.html -o $masterlist -nt $webdir/mirror/list.html ] ; then
#	$prog -m $masterlist -t html > $webdir/mirror/list.html
#	echo Updated web version of mirrors file
#fi
if [ ! -L $webdir/mirror/list.html ]; then
	rm $webdir/mirror/list.html
	ln -s list.en.html $webdir/mirror/list.html
fi

#if [ ! -f $webdir/mirror/list-full.html -o $masterlist -nt $webdir/mirror/list-full.html ] ; then
#	$prog -m $masterlist -t fullmethods > $webdir/mirror/list-full.html
#	echo Updated web version of full mirrors file
#fi
if [ ! -L $webdir/mirror/list-full.html ]; then
	rm $webdir/mirror/list-full.html
	ln -s list-full.en.html $webdir/mirror/list-full.html
fi

#if [ ! -f $webdir/mirror/list-non-US.html -o $masterlist -nt $webdir/mirror/list-non-US.html ] ; then
#	$prog -m $masterlist -t nonushtml > $webdir/mirror/list-non-US.html
#	echo Updated web version of non-US mirrors file
#fi
if [ ! -L $webdir/mirror/list-non-US.html ]; then
	rm $webdir/mirror/list-non-US.html
	ln -s list-non-US.en.html $webdir/mirror/list-non-US.html
fi

# ftp-master:/org/ftp.debian.org/katie/update-mirrorlists updates
# README.mirrors.{html,txt} for the FTP site

echo
