#!/bin/sh -e

# this script re-creates README.mirrors.html, README.non-US.html and
# mirrors_full.html files in case Mirrors.masterlist was modified
# (updated from CVS in 4webwml)

. `dirname $0`/../common.sh

prog=$webtopdir/webwml/english/mirror/mirror_list.pl
masterlist=$webtopdir/webwml/english/mirror/Mirrors.masterlist

if [ ! -f $webdir/mirror/list.html -o $masterlist -nt $webdir/mirror/list.html ] ; then
	$prog -m $masterlist -t html > $webdir/mirror/list.html
	echo Updated web version of mirrors file
fi

if [ ! -f $webdir/mirror/list-non-US.html -o $masterlist -nt $webdir/mirror/list-non-US.html ] ; then
	$prog -m $masterlist -t nonushtml > $webdir/mirror/list-non-US.html
	echo Updated web version of non-US mirrors file
fi

if [ ! -f $webdir/mirror/list-full.html -o $masterlist -nt $webdir/mirror/list-full.html ] ; then
	$prog -m $masterlist -t fullmethods > $webdir/mirror/list-full.html
	echo Updated web version of full mirrors file
fi

# ftp-master:/org/ftp.debian.org/katie/update-mirrorlists updates
# README.mirrors.{html,txt} for the FTP site

echo
