#!/bin/bash

# update the world map of developer locations

. `dirname $0`/../common.sh
markers=/var/lib/misc/`hostname -f`/markers

echo "Updating markers file"
install -g debwww -m 664 $markers $webdir/devel/developers.coords

echo "Generating the config file"
config=`mktemp`
trap "rm $config" EXIT
cat >$config <<EOF
[earth]
"Earth"

shade=100
map=earth.jpg
marker_file=$markers
marker_color=yellow
EOF

echo "Updating map"
cd $crondir/datafiles
time xplanet -config $config -projection rectangular \
     -output $webdir/devel/developers.map.jpeg -geometry 750x450 -num_times 1

echo
