#!/bin/bash

# update the world map of developer locations

. `dirname $0`/../common.sh
markers=/var/lib/misc/`hostname -f`/markers

echo "Updating markers file"
install -g debwww -m 664 $markers $webdir/devel/developers.coords

echo "Updating map"
cd $crondir/datafiles
# This needs the file delegates.mgk to be in the same dir
time xplanet --image $crondir/datafiles/earth.jpg --shade 100 \
             --markerfile $markers --color red \
             --output $webdir/devel/developers.map.jpeg --geometry 750x450

echo
