#!/bin/bash -e

# This file updates the doc/manuals/ directory of the web pages
# with the current stuff

# we used to do this with CVS, now it's SVN
# cvs update -d -P &> cvs.log

. `dirname $0`/../common.sh

cd $webtopdir/ddp-svn

#  Please notice that using svn export will _not_ remove files that you
# svn rm'ed from the repository so it means it will keep cruft around (and
# through that might cause problems).
echo "Running the DDP SVN export... (at `date`)"
svn export --force svn://svn.debian.org/svn/ddp/manuals . &> svn.log

echo "Running the DDP SVN build... (at `date`)"
make -C trunk publish &> make.log

echo "DDP update and build finished at `date`"

# Workaround devref bug (links done to .html instead of .$lang.html) and
# content neogciation
webdocdir=$webdir/doc/manuals
for lang in en de fr ja
do
	for doc in $webdocdir/developers-reference/*.$lang.html
	do
		ln -sf $(basename "$doc" .$lang.html).$lang.html $webdocdir/developers-reference/$(basename "$doc" .$lang.html).html.$lang
	done
		ln -sf developers-reference.$lang.pdf $webdocdir/developers-reference/developers-reference.pdf.$lang
		ln -sf developers-reference.$lang.txt $webdocdir/developers-reference/developers-reference.txt.$lang
done

echo
