#!/bin/bash -e

# This file updates the doc/manuals/ directory of the web pages
# with the current CVS stuff

. `dirname $0`/../common.sh

cd $webtopdir/ddp

echo "Running the DDP CVS update..."
cvs update -d -P &> cvs.log

echo "Running the DDP CVS build..."
make -C manuals.sgml clean publish &> make.log

echo
