#!/bin/bash -e

# This file updates the doc/ directory of the web pages

# Oh, how I wish the -doc people would maintain this. -- Jay Treacy
# There ain't no such thing as the -doc people these days :/ -- Josip Rodin

. `dirname $0`/../common.sh
webdocdir=$webdir/doc
ftpdocdir=$ftpdir/doc

cd $crondir/tmp

echo -n "Installing documents:"

test -d $webdocdir/packaging-manuals || install -d -g debwww -m 2775 $webdocdir/packaging-manuals

echo -n " debian-faq"
ln -s manuals/debian-faq $webdocdir/FAQ

# the next few are from the same debian-policy .deb package
dpdeb=`ls -1 $ftpdir/pool/main/d/debian-policy/debian-policy_*.deb | tail -1`
dpkg-deb -x $dpdeb dp

echo -n " policy-manual"
test -d $webdocdir/debian-policy || install -d -g debwww -m 2775 $webdocdir/debian-policy
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/policy.html/* $webdocdir/debian-policy/

echo -n " fhs"
test -d $webdocdir/packaging-manuals/fhs || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/fhs
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/fhs.html/* $webdocdir/packaging-manuals/fhs/

echo -n " virtual-package-names"
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/virtual-package-names-list.txt.gz $webdocdir/packaging-manuals
gunzip $webdocdir/packaging-manuals/virtual-package-names-list.txt.gz

echo -n " menu-policy"
test -d $webdocdir/packaging-manuals/menu-policy || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/menu-policy
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/menu-policy.html/* $webdocdir/packaging-manuals/menu-policy/

echo -n " perl-policy"
test -d $webdocdir/packaging-manuals/perl-policy || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/perl-policy
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/perl-policy.html/* $webdocdir/packaging-manuals/perl-policy/

echo -n " mime-policy"
test -d $webdocdir/packaging-manuals/mime-policy || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/mime-policy
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/mime-policy.html/* $webdocdir/packaging-manuals/mime-policy/

echo -n " libc6-migration"
install -p -g debwww -m 664 dp/usr/share/doc/debian-policy/libc6-migration.txt.gz $webdocdir/packaging-manuals/
gunzip $webdocdir/packaging-manuals/libc6-migration.txt.gz

# done with the debian-policy package stuff
rm -rf dp

echo -n " developers-reference"
ln -s manuals/developers-reference $webdocdir/developers-reference

echo -n " maint-guide"
ln -s manuals/maint-guide $webdocdir/maint-guide

echo -n " build-essential"
bedeb=`ls -1 $ftpdir/pool/main/b/build-essential/build-essential_*.deb | tail -1`
dpkg-deb -x $bedeb be
install -p -g debwww -m 664 be/usr/share/doc/build-essential/list $webdocdir/packaging-manuals/build-essential
rm -rf be

echo -n " menu"
medeb=`ls -1 $ftpdir/pool/main/m/menu/menu_*.deb | tail -1`
dpkg-deb -x $medeb me
test -d $webdocdir/packaging-manuals/menu.html || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/menu.html
install -p -g debwww -m 664 me/usr/share/doc/menu/html/* $webdocdir/packaging-manuals/menu.html/
rm -rf me

echo -n " emacsen-policy"
epdeb=`ls -1 $ftpdir/pool/main/e/emacsen-common/emacsen-common_*.deb | tail -1`
dpkg-deb -x $epdeb ep
zcat ep/usr/share/doc/emacsen-common/debian-emacs-policy.gz > ep/debian-emacs-policy
install -p -g debwww -m 664 ep/debian-emacs-policy $webdocdir/packaging-manuals/
rm -rf ep

echo -n " java-policy"
jcdeb=`ls -1 $ftpdir/pool/main/j/java-common/java-common_*.deb | tail -1`
dpkg-deb -x $jcdeb jc
test -d $webdocdir/packaging-manuals/java-policy || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/java-policy
install -p -g debwww -m 664 jc/usr/share/doc/java-common/debian-java-policy/*.html $webdocdir/packaging-manuals/java-policy/
rm -rf jc

echo -n " dpkg-internals"
dddeb=`ls -1 $ftpdir/pool/main/d/dpkg/dpkg-doc_*.deb | tail -1`
dpkg-deb -x $dddeb dd
test -d $webdocdir/packaging-manuals/dpkg-internals || install -d -g debwww -m 2775 $webdocdir/packaging-manuals/dpkg-internals
install -p -g debwww -m 664 dd/usr/share/doc/dpkg/internals/* $webdocdir/packaging-manuals/dpkg-internals/
rm -rf dd

# still not accounted for: libc5-libc6-Mini-HOWTO
# joy has sent a mail to Craig Sanders asking about that and the rest of the
# bo->hamm upgrade files to be added to people.d.o/~cas/ but there was no reply
# (this also affects things under /releases/hamm)

echo
