#!/bin/bash -e

# This file updates the doc/manuals/ directory of the web pages
# with the current stuff

# we used to do this with CVS, now it's SVN
# cvs update -d -P &> cvs.log

. `dirname $0`/../common.sh

cd $webtopdir/ddp-svn

echo "Running the DDP SVN update..."
svn update &> svn.log

echo "Running the DDP SVN build..."
make -C trunk publish &> make.log

echo
