#!/bin/bash -e

# This file updates the doc/ directory of the web pages

# Oh, how I wish the -doc people would maintain this. -- Jay Treacy
# There ain't no such thing as the -doc people these days :/ -- Josip Rodin

# ftpdir is *not* the full archive, it's populated by 1ftpfiles

. `dirname $0`/../common.sh
webdocdir=$webdir/doc
ftpdocdir=$ftpdir/doc

cd $crondir/tmp

echo -n "Installing documents:"

test -d $webdocdir/packaging-manuals || install -d -m 2775 $webdocdir/packaging-manuals

echo -n " debian-faq"
ln -sf manuals/debian-faq $webdocdir/FAQ

# the next few are from the same debian-policy .deb package
dpdeb=`ls -t1 $ftpdir/pool/main/d/debian-policy/debian-policy_*.deb | head -1`
dpkg-deb -x $dpdeb dp

install_policy_doc () {
    document="$1"
    target="$2"
    target="$webdocdir/$target/"
    pathprefix="$3/"
    htmlsingle="$4"
    
    echo -n " $document"
    test -d "$target" || install -d -m 2775 "$target"
    if [ -n "$htmlsingle" ]; then
    	install -p -m 664 dp/usr/share/doc/debian-policy/${pathprefix}${document}.html "$target"
    else
    	install -p -m 664 dp/usr/share/doc/debian-policy/${pathprefix}${document}.html/* "$target"
    fi
    for format in ps pdf txt; do
	file="dp/usr/share/doc/debian-policy/${pathprefix}${document}.${format}.gz"
	[ -e $file ] && \
	    install -p -m 664 "$file" "$target"
    done
}

install_policy_doc policy debian-policy
install_policy_doc fhs-2.3 packaging-manuals/fhs fhs yes
install_policy_doc menu-policy packaging-manuals/menu-policy
install_policy_doc perl-policy packaging-manuals/perl-policy
install_policy_doc mime-policy packaging-manuals/mime-policy

echo -n " upgrading-checklist"
zcat dp/usr/share/doc/debian-policy/upgrading-checklist.txt.gz > dp/upgrading-checklist.txt
install -p -m 664 dp/upgrading-checklist.txt $webdocdir/packaging-manuals/

echo -n " virtual-package-names"
zcat dp/usr/share/doc/debian-policy/virtual-package-names-list.txt.gz > dp/virtual-package-names-list.txt
install -p -m 664 dp/virtual-package-names-list.txt $webdocdir/packaging-manuals/

echo -n " debconf_specification"
install -p -m 664 dp/usr/share/doc/debian-policy/debconf_specification.html $webdocdir/packaging-manuals/

echo -n " libc6-migration"
zcat dp/usr/share/doc/debian-policy/libc6-migration.txt.gz > dp/libc6-migration.txt
install -p -m 664 dp/libc6-migration.txt $webdocdir/packaging-manuals/

# done with the debian-policy package stuff
rm -rf dp

echo -n " maint-guide"
ln -sf manuals/maint-guide $webdocdir/maint-guide

echo -n " build-essential"
bedeb=`ls -t1 $ftpdir/pool/main/b/build-essential/build-essential_*.deb | head -1`
dpkg-deb -x $bedeb be
install -p -m 664 be/usr/share/doc/build-essential/list $webdocdir/packaging-manuals/build-essential
rm -rf be

echo -n " menu"
medeb=`ls -t1 $ftpdir/pool/main/m/menu/menu_*.deb | head -1`
dpkg-deb -x $medeb me
test -d $webdocdir/packaging-manuals/menu.html || install -d -m 2775 $webdocdir/packaging-manuals/menu.html
install -p -m 664 me/usr/share/doc/menu/html/* $webdocdir/packaging-manuals/menu.html/
rm -rf me

echo -n " emacsen-policy"
epdeb=`ls -t1 $ftpdir/pool/main/e/emacsen-common/emacsen-common_*.deb | head -1`
dpkg-deb -x $epdeb ep
zcat ep/usr/share/doc/emacsen-common/debian-emacs-policy.gz > ep/debian-emacs-policy
install -p -m 664 ep/debian-emacs-policy $webdocdir/packaging-manuals/
rm -rf ep

echo -n " java-policy"
jcdeb=`ls -t1 $ftpdir/pool/main/j/java-common/java-common_*.deb | head -1`
dpkg-deb -x $jcdeb jc
test -d $webdocdir/packaging-manuals/java-policy || install -d -m 2775 $webdocdir/packaging-manuals/java-policy
install -p -m 664 jc/usr/share/doc/java-common/debian-java-policy/*.html $webdocdir/packaging-manuals/java-policy/
rm -rf jc

# deprecated dpkg-doc from snapshot.debian.org
echo -n " dpkg-internals"
dddeb=`ls -t1 $ftpdir/debian/*/pool/main/d/dpkg/dpkg-doc_*.deb | head -1`
dpkg-deb -x $dddeb dd
test -d $webdocdir/packaging-manuals/dpkg-internals || install -d -m 2775 $webdocdir/packaging-manuals/dpkg-internals
install -p -m 664 dd/usr/share/doc/dpkg/internals/* $webdocdir/packaging-manuals/dpkg-internals/
rm -rf dd

echo -n " python-policy"
pydeb=`ls -t1 $ftpdir/pool/main/p/python-defaults/python_*.deb | head -1`
dpkg-deb -x $pydeb py
test -d $webdocdir/packaging-manuals/python-policy || install -d -m 2775 $webdocdir/packaging-manuals/python-policy
install -p -m 664 py/usr/share/doc/python/python-policy.html/* $webdocdir/packaging-manuals/python-policy/
rm -rf py

echo -n " debian-refcard"
drdeb=`ls -t1 $ftpdir/pool/main/r/refcard/debian-refcard_*.deb | head -1`
dpkg-deb -x $drdeb dr
test -d $webdocdir/manuals/refcard || install -d -m 2775 $webdocdir/manuals/refcard
for refcardfile in dr/usr/share/doc/debian-refcard/*a4.pdf.gz ; do
	# rename from refcard-fr-a4.pdf.gz to refcard.fr.pdf as expected by the website
	futurename=`echo $refcardfile | sed 's/refcard-\(\w*\)-a4.pdf.gz/refcard.\1.pdf/'`
	gunzip -f $refcardfile && mv dr/usr/share/doc/debian-refcard/$(basename $refcardfile .gz) $futurename
done
install -p -m 664 dr/usr/share/doc/debian-refcard/*pdf $webdocdir/manuals/refcard/
rm -rf dr

echo

# still not accounted for: libc5-libc6-Mini-HOWTO
# joy has sent a mail to Craig Sanders asking about that and the rest of the
# bo->hamm upgrade files to be added to people.d.o/~cas/ but there was no reply
# (this also affects things under /releases/hamm)

echo
