#!/bin/bash -e

. `dirname $0`/../common.sh

notesdir=$webtopdir/release-notes

echo "Running the full release notes build... (at `date`)"

savelog -g debwww -m 664 $notesdir/build.log >/dev/null

date > $notesdir/build.log

# sarge isn't currently build by default since the current build
# system doesn't allow to rebuild only if necessary. If a rebuild
# is needed just add it here
for release in etch; do
    echo "rebuilding the release notes for $release" >> $notesdir/build.log
    (cd $notesdir/$release && cvs update -d -P) >> $notesdir/build.log 2>&1
    make -C $notesdir/$release publish \
	 PUBLISHTARBALL=yes PUBLISHDIR=$webtopdir/www/releases/$release >> $notesdir/build.log 2>&1
done

(cd $notesdir/$release && svn update) >> $notesdir/build.log 2>&1
make -C $notesdir/lenny publish \
    PUBLISHTARBALL=yes PUBLISHDIR=$webtopdir/www/releases/lenny >> $notesdir/build.log 2>&1

date >> $notesdir/build.log

echo "Full release notes build finished (at `date`)"

echo
