#!/bin/bash -e

. `dirname $0`/../common.sh

notesdir=$webtopdir/release-notes

date > $notesdir/build.log

# sarge isn't currently build by default since the current build
# system doesn't allow to rebuild only if necessary. If a rebuild
# is needed just add it here
for release in etch; do
    echo "rebuilding the release notes for $release" >> $notesdir/build.log
    (cd $notesdir/$release && cvs update -d -P) >> $notesdir/build.log 2>&1
    make -C $notesdir/$release publish \
	 PUBLISHTARBALL= PUBLISHDIR=$webtopdir/www/releases/$release >> $notesdir/build.log 2>&1
done

date >> $notesdir/build.log

echo
