#!/bin/bash

. `dirname $0`/../common.sh

cd $webtopdir/webwml

umask 002

# remove .html files that have not corresponding .wml file and aren't in CVS

./remove_stale.pl -d

# this script finds new files and touches old ones so that the list of
# languages at the bottom is updated to include the new file.

$webtopdir/webwml/touch_old_files.pl -d

echo
