#!/bin/bash

. `dirname $0`/../common.sh

cd $webtopdir/webwml

umask 002

# remove .html files that have not corresponding .wml file and aren't in CVS

savelog -g debwww -m 664 $crondir/log/remove_stale.log >/dev/null
echo "Running remove_stale.pl... (at `date`)"
time ./remove_stale.pl -d > $crondir/log/remove_stale.log

# this script finds added and removed files and touches old ones so
# that the list of languages at the bottom is updated to include
# added files and omit removed files.

savelog -g debwww -m 664 $crondir/log/touch_files.log >/dev/null
echo "Running touch_files.pl... (at `date`)"
time ./touch_files.pl -d > $crondir/log/touch_files.log

echo
