#! /bin/sh

# This script must be run by someone with a suitable entry in sudoers, e.g.:
#
# %debwww klecker=(archvsync) NOPASSWD:/home/archvsync/webmirrors/runmirrors

sudo -u archvsync /home/archvsync/webmirrors/runmirrors
