#! /bin/sh

from='Debian Webmaster <webmaster@debian.org>'
mailto=joey@infodrom.north.de
xloop=debian-www@lists.debian.org
regexp='\(Break\|ignored\)'

logfile=/org/www.debian.org/cron/wml_run.log
if grep -q "$regexp" $logfile
then
    (
      echo "From: $from"
      echo "To: $mailto"
      echo "X-Loop: $xloop"
      echo "Subject: webwml failed"
      echo
      grep -A 4 -B 15 "$regexp" $logfile
    ) | /usr/sbin/sendmail -t
fi

logfile=/org/www.debian.org/bf/woody/make.log
if grep -q "$regexp" $logfile
then
    (
      echo "From: $from"
      echo "To: $mailto"
      echo "X-Loop: $xloop"
      echo "Subject: woody bf documentation build failed"
      echo
      grep -A 4 -B 15 "$regexp" $logfile
    ) | /usr/sbin/sendmail -t
fi
