# This Makefile should need no changes from webwml/english/ports/mips/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/hurd
SUBS=extra-files

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/hurd/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
