# This Makefile should need no changes from webwml/english/security/audit/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../..
CUR_DIR=security/audit/2004

../data/2004.inc: 
	../make-advisories ../data


all:: ../data/2004.inc
install:: all


include $(WMLBASE)/Make.lang
