# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=..
CUR_DIR=logos
SUBS=

GETTEXTFILES += others.mo

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/template.wml \
  $(ENGLISHDIR)/logos/index.data \
  $(GETTEXTDEP) \
  $(ENGLISHDIR)/logos/openlogo-25.jpg $(ENGLISHDIR)/logos/openlogo-nd-25.jpg \
  $(ENGLISHDIR)/logos/officiallogo-25.jpg $(ENGLISHDIR)/logos/officiallogo-nd-25.jpg \
  $(ENGLISHDIR)/logos/button-1.gif $(ENGLISHDIR)/logos/button-2.gif \
  $(ENGLISHDIR)/logos/button-3.jpg $(ENGLISHDIR)/logos/button-k1.png \
  $(ENGLISHDIR)/logos/button-k2.png $(ENGLISHDIR)/logos/banner_64.gif \
  $(ENGLISHDIR)/logos/banner_wp.gif $(ENGLISHDIR)/logos/banner_h.gif \
  $(ENGLISHDIR)/logos/banner_a.gif $(ENGLISHDIR)/logos/banner_v.jpg \
  $(ENGLISHDIR)/logos/gnuart.png $(ENGLISHDIR)/logos/debart_logo_04.png
