# This Makefile should need no changes from webwml/english/News/press/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=News/press
# list any subdirectories in the following variable. If a listed directory
# exists, it must contain a Makefile, or make gives an error
SUBS=

include $(WMLBASE)/Make.lang

include $(ENGLISHDIR)/News/press/Makefile.press
