# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../../..
CUR_DIR=devel/hamradio/get
SUBS=

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/basic.wml

metapackages.$(LANGUAGE).html: metapackages.wml $(TEMPLDIR)/basic.wml

live.$(LANGUAGE).html: live.wml $(TEMPLDIR)/basic.wml
