#use wml::debian::blends::hamradio
#use wml::debian::translation-check translation="1.1" maintainer="Ana Custura"
{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Debian&nbsp;Hamradio&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">Despre</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Arhive</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Contact</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Obține&nbsp;Blend-ul</a>
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Descarcă&nbsp;imagini&nbsp;live</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Folosește&nbsp;pachetele&nbsp;meta</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Documentație</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Manualul&nbsp;Debian&nbsp;Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Suport</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Pentru programatori</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Echipa Hamradio</a></li>
        <li><a href="<hamradio-maintguide-html/>">Ghid pentru menținătorii Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Distractiv</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/blends/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
