# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../../../..
CUR_DIR=international/spanish/contrib/paqifaz-capturas
SUBS=

include $(WMLBASE)/Make.lang

