#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Debian&nbsp;Hamradio&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">À&nbsp;propos&nbsp;du&nbsp;mélange</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Archives&nbsp;des&nbsp;Nouvelles</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Contact</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Obtention&nbsp;du&nbsp;mélange</a>
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Téléchargement&nbsp;d’images&nbsp;autonomes</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Utilisation&nbsp;des&nbsp;métapaquets</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Documentation</a>
        <ul>
        <li><a href="$(HOME)/doc/manuals/hamradio-handbook/">Manuel&nbsp;pour&nbsp;radioamateur&nbsp;Debian</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Aide</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Développement</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Équipe&nbsp;des&nbsp;responsables&nbsp;radioamateurs</a></li>
        <li><a href="$(HOME)/blends/hamradio/doc/hamradio-maintguide/">Guide&nbsp;des&nbsp;responsables&nbsp;radioamateurs</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Détente</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/blends/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
