<p>Andere BTS pages:

<ul>
  <li><a href="./">Bug traceer systeem hoofdpagina.</a>
  <li><a href="Reporting">Instructies voor het melden van bugs.</a>
  <li><a href="Access">Methoden om bug rapporten te bekijken.</a>
  <li><a href="Developer">Informatie voor ontwikkelaars over het bug traceer
      systeem.</a>
  <li><a href="server-control">Ontwikkelaarsinformatie over het bewerken van
      bugs via een e-mailinterface.</a>
  <li><a href="server-refcard">Mailservers' referentiekaart.</a>
  <li><a href="server-request">Bug rapporten verkrijgen via e-mail.</a>
#  <li><a href="db/ix/full.html">Volledige lijst van onopgeloste en recente bugs.</a>
#  <li><a href="db/ix/packages.html">Pakketten met bugs.</a>
#  <li><a href="db/ix/maintainers.html">Ontwikkelaars met pakketten die bugs bevatten.</a>
</ul>
