# This Makefile should need no changes from webwml/english/devel/join/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=devel/join
SUBS=

include $(WMLBASE)/Make.lang

nm-step1.$(LANGUAGE).html nm-step2.$(LANGUAGE).html \
nm-step3.$(LANGUAGE).html nm-step4.$(LANGUAGE).html \
nm-step5.$(LANGUAGE).html: $(ENGLISHDIR)/devel/join/nm-steps.inc \
 $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
