# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=devel/join
SUBS=

include $(WMLBASE)/Make.lang

nm-step1.$(LANGUAGE).html nm-step2.$(LANGUAGE).html \
nm-step3.$(LANGUAGE).html nm-step4.$(LANGUAGE).html \
nm-step5.$(LANGUAGE).html: $(ENGLISHDIR)/devel/join/nm-steps.inc \
 $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
