#use wml::debian::common_tags
#use wml::debian::submenu

<bind-gettext-domain domain="others" />

<define-menu-item name="newmaint">
  <gettext domain="others">New Maintainers' Corner</gettext>
</define-menu-item>

<define-menu-item name="step1"><gettext domain="others">Step 1</gettext></define-menu-item>
<define-menu-item name="step2"><gettext domain="others">Step 2</gettext></define-menu-item>
<define-menu-item name="step3"><gettext domain="others">Step 3</gettext></define-menu-item>
<define-menu-item name="step4"><gettext domain="others">Step 4</gettext></define-menu-item>
<define-menu-item name="step5"><gettext domain="others">Step 5</gettext></define-menu-item>
<define-menu-item name="step6"><gettext domain="others">Step 6</gettext></define-menu-item>
<define-menu-item name="step7"><gettext domain="others">Step 7</gettext></define-menu-item>

<define-menu-item name="nm-checklist">
  <gettext domain="others">Applicants' checklist</gettext>
</define-menu-item>

<menu-item name="newmaint" basename="newmaint">
<menu-item name="nm-checklist" basename="nm-checklist">
<menu-item name="step1" basename="nm-step1">
<menu-item name="step2" basename="nm-step2">
<menu-item name="step3" basename="nm-step3">
<menu-item name="step4" basename="nm-step4">
<menu-item name="step5" basename="nm-step5">
<menu-item name="step6" basename="nm-step6">
<menu-item name="step7" basename="nm-step7">
