<p>D'altres pàgines del BTS:

<ul>
  <li><a href="./">Pàgina principal de continguts del sistema de seguiment d'errors.</a>
  <li><a href="Reporting">Instruccions per a reportar errors.</a>
  <li><a href="Access">Accedint a la bitàcola del sistema de seguiment d'errors.</a>
  <li><a href="Developer">Informació per als desenvolupadors sobre el sistema de
      seguiment d'errors.</a>
  <li><a href="server-control">Informació per als desenvolupadors de com usar la
      interfície de correu per al control dels errors.</a>
  <li><a href="server-refcard">Targeta de referència pel servidor de correu.</a>
  <li><a href="server-request">Demanant informes d'error per correu.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
