<p>D'altres pàgines del BTS:

<ul>
  <li><a href="./">Pàgina principal de continguts del sistema de seguiment d'errors.</a>
  <li><a href="Reporting">Instruccions per a reportar errors.</a>
  <li><a href="Access">Accedint a la bitàcola del sistea de seguiment d'errors.</a>
  <li><a href="Developer">Informació pels desenvolupadors sobre el sistema de
      seguiment d'errors.</a>
  <li><a href="server-control">Informació pels desenvolupadors de com usar la
      interfície de correu pel control dels errors.</a>
  <li><a href="server-refcard">Targeta de referéncia pel servidor de correu.</a>
  <li><a href="server-request">Requerint informes d'errror per correu.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
