# This Makefile should need no changes from webwml/english/ports/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=ports
SUBS=alpha arm beowulf hppa hurd laptops m68k mips powerpc sparc sparc64

include $(WMLBASE)/Make.lang

