# This Makefile should need no changes from webwml/english/international/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=international
SUBS=Chinese finnish french german italian japanese korean spanish turkish

include $(WMLBASE)/Make.lang


