#use wml::debian::translation-check translation="1.2"

<p>Druge BTS stranice:

<ul>
  <li><a href="./">Sustav praæenja bugova, glavna stranica sadr¾aja.</a>
  <li><a href="Reporting">Upute za prijavljivanje bugova.</a>
  <li><a href="Access">Pristupanje izvje¹tajima u sustavu praæenja bugova.</a>
  <li><a href="Developer">Informacije o sustavu praæenja bugova za
      razvijatelje.</a>
  <li><a href="server-control">Informacije za razvijatelje o rukovanju
      bugovima koristeæi e-mail.</a>
  <li><a href="server-refcard">Kratke upute za e-mail poslu¾itelje.</a>
  <li><a href="server-request">Zahtijevanje bug izvje¹taja e-mailom.</a>
</ul>
