#use wml::debian::translation-check translation="1.1"

<p>Druge BTS stranice:

<ul>
  <li><a href="./">Sustav praæenja bugova, glavna stranica sadr¾aja.</a>
  <li><a href="Reporting">Instrukcije za prijavljivanje bugova.</a>
  <li><a href="Access">Pristupanje bug izvje¹tajima drugaèije nego WWW-om.</a>
  <li><a href="Developer">Informacije o sustavu praæenja bugova za
      razvijatelje.</a>
  <li><a href="server-control">Razvijateljske informacije o manipulaciji
      bugovima koristeæi e-mail kontrolno suèelje.</a>
  <li><a href="server-refcard">Referentna kartica za e-mail poslu¾itelj.</a>
  <li><a href="server-request">Zahtijevanje bug izvje¹taja e-mailom.</a>
</ul>
