# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=devel/hamradio
SUBS=News Pics

include $(WMLBASE)/Make.lang

index.$(LANGUAGE).html: index.wml $(TEMPLDIR)/basic.wml

live.$(LANGUAGE).html: live.wml $(TEMPLDIR)/basic.wml

dev.$(LANGUAGE).html: dev.wml $(TEMPLDIR)/basic.wml

contact.$(LANGUAGE).html: contact.wml $(TEMPLDIR)/basic.wml
