#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/devel/hamradio/">Debian&nbsp;Hamradio&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/devel/hamradio/about">About</a></li>
      <li><a href="$(HOME)/devel/hamradio/News/">News&nbsp;Archives</a></li>
      <li><a href="$(HOME)/devel/hamradio/contact">Contact</a></li>
      <li><a href="$(HOME)/devel/hamradio/get/">Getting&nbsp;the&nbsp;Blend</a>
         <ul>
         <li><a href="$(HOME)/devel/hamradio/get/live">Download&nbsp;live&nbsp;images</a></li>
         <li><a href="$(HOME)/devel/hamradio/get/metapackages">Using&nbsp;the&nbsp;metapackages</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/devel/hamradio/docs/">Documentation</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Debian&nbsp;Hamradio&nbsp;Handbook</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/devel/hamradio/support">Support</a></li>
      <li><a href="$(HOME)/devel/hamradio/dev">Development</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Hamradio Maintainers Team</a></li>
        <li><a href="<hamradio-maintguide-html/>">Hamradio Maintainers Guide</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/devel/hamradio/fun">Fun</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/devel/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
