#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="alpha">
   [EN:Debian for Alpha:]
   [AR:Debian for Alpha:]
   [DA:Debian til Alpha:]
   [DE:Debian für Alpha:]
   [EL:Debian for Alpha:]
   [EO:Debian for Alpha:]
   [ES:Debian para Alpha:]
   [FI:Debian for Alpha:]
   [FR:Debian for Alpha:]
   [HR:Debian for Alpha:]
   [HU:Debian for Alpha:]
   [IT:Debian per Alpha:]
   [JA:Debian for Alpha:]
   [KO:Debian for Alpha:]
   [NL:Debian for Alpha:]
   [NO:Debian for Alpha:]
   [PL:Debian for Alpha:]
   [PT:Debian para Alpha:]
   [RO:Debian for Alpha:]
   [RU:Debian for Alpha:]
   [SV:Debian för Alpha:]
   [TR:Debian for Alpha:]
   [ZH:Debian for Alpha:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="alpha"         basename="index">
<menu-item name="news"          basename="news">
<menu-item name="status"        basename="port-status">
<menu-item name="systems"       basename="sys_types">
<menu-item name="links"         basename="links">

