#use wml::debian::blends::gis

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/gis/">Debian&nbsp;GIS&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/gis/about">About</a></li>
      <li><a href="$(HOME)/blends/gis/contact">Contact</a></li>
      <li><a href="$(HOME)/blends/gis/get/">Getting&nbsp;the&nbsp;Blend</a>
         <ul>
         <li><a href="$(HOME)/blends/gis/get/live">Download&nbsp;live&nbsp;images</a></li>
         <li><a href="$(HOME)/blends/gis/get/metapackages">Using&nbsp;the&nbsp;metapackages</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/gis/support">Support</a></li>
      <li><a href="$(HOME)/blends/gis/deriv">Derivatives</a></li>
      <li><a href="https://wiki.debian.org/DebianGIS#Development">Development</a>
        <ul>
        <li><a href="<gis-policy-html/>">GIS Team Policy</a></li>
        </ul>
      </li>
      <li><a href="https://twitter.com/DebianGIS"><img src="$(HOME)/blends/gis/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
