<p>Inne strony WWW systemu śledzenia błędów:

<ul>
  <li><a href="./">Główna strona systemu śledzenia błędów.</a>
  <li><a href="Reporting">Jak zgłosić błąd.</a>
  <li><a href="Access">Dostęp do zgłoszonych błędów.</a>
  <li><a href="Developer">Instrukcje użycia systemu dla rozwijających.</a>
  <li><a href="server-control">Instrukcje dla rozwijających dotyczące
      manipulacji na zgłoszeniach przy pomocy poczty elektronicznej.</a>
  <li><a href="server-refcard">Polecenia serwera pocztowego.</a>
  <li><a href="server-request">Otrzymywanie zgłoszeń pocztą elektroniczną.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
