<p>Inne strony WWW systemu ¶ledzenia b³êdów:

<ul>
  <li><a href="./">G³ówna strona systemu ¶ledzenia b³êdów.</a>
  <li><a href="Reporting">Jak zg³osiæ b³±d.</a>
  <li><a href="Access">Dostêp do zg³oszonych b³êdów.</a>
  <li><a href="Developer">Instrukcje u¿ycia systemu dla rozwijaj±cych.</a>
  <li><a href="server-control">Instrukcje dla rozwijaj±cych dotycz±ce
      manipulacji na zg³oszeniach przy pomocy poczty elektronicznej.</a>
  <li><a href="server-refcard">Polecenia serwera pocztowego.</a>
  <li><a href="server-request">Otrzymywanie zg³oszeñ poczt± elektroniczn±.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
