#use wml::debian::translation-check translation="1.3"

<p>További oldalak:</p>
<ul>

<li><a href="./">A hibakövető rendszer fő oldala</a></li>
<li><a href="Reporting">Hogyan lehet hibát bejelenteni?</a></li>
<li><a href="Access">A hibakövető rendszer naplóinak elérése</a></li>
<li><a href="Developer">Információk a hibafeldolgozó rendszerről fejlesztők részére</a></li>
<li><a href="server-control">A hibafeldolgozás vezérlése e-mailen keresztül</a></li>
<li><a href="server-refcard">A levelezőszerverek referenciakártyája</a></li>
<li><a href="server-request">A hibabejelentések lekérdezése e-mailen keresztül</a></li>
#<li><A href="db/ix/full.html">A kiemelkedő ("outstanding") és
#legújabb ("recent") hibalapok teljes felsorolása</a></li>
#
#<li><A href="db/ix/packages.html">Csomagok hibalappal</a></li>
#
#<li><A href="db/ix/maintainers.html">Hibalapos csomagok
#karbantartói</a></li>
#
#<li><A href="../">A Debian GNU/Linux kezdőoldala.</a></li>
#
</ul>
