#use wml::debian::translation-check translation="1.2"

<hr>
További oldalak:
<ul>

<li><A href="./">A hibakövetõ rendszer fõ oldala</A>
<li><a href="Reporting">Hogyan lehet hibát bejelenteni?</a>
<li><A href="Access">A hibakövetõ rendszer naplóinak
elérése</A>
<li><A href="Developer">Információk a hibafeldolgozó
rendszerrõl fejlesztõk részére</A>
<li><a href="server-control">A hibafeldolgozás vezérlése e-mailen keresztül</a>
<li><a href="server-refcard">A levelezõszerverek referenciakártyája</a>
<li><a href="server-request">A hibabejelentések lekérdezése e-mailen keresztül</a>
#<li><A href="db/ix/full.html">A kiemelkedõ ("outstanding") és
#legújabb ("recent") hibalapok teljes felsorolása</A>
#
#<li><A href="db/ix/packages.html">Csomagok hibalappal</A>
#
#<li><A href="db/ix/maintainers.html">Hibalapos csomagok
#karbantartói</A>
#
#<li><A href="../">A Debian GNU/Linux kezdõoldala.</A>
#
</ul>
