# This Makefile should need no changes from webwml/english/y2k/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=y2k
SUBS=

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: ../../english/y2k/index.data
extra.$(LANGUAGE).html: ../../english/y2k/extra.data
