# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=international/l10n
SUBS=po po-debconf po4a

GETTEXTFILES += l10n.mo

include $(WMLBASE)/Make.lang

