# This Makefile should need no changes from webwml/english/international/l10n/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=international/l10n
SUBS=po templates

include $(WMLBASE)/Make.lang

