# translation-check version="1.2"
<p>Weitere Seiten der Fehlerdatenbank:

<ul>
  <li><a href="./">Hauptseite der Fehlerdatenbank.</a>
  <li><a href="Reporting">Instruktionen für das Melden von Fehlern.</a>
  <li><a href="Access">Zugriff auf Protokolle.</a>
  <li><a href="Developer">Informationen für Entwickler.</a>
  <li><a href="server-control">Entwickler-Informationen zur Manipulation von Fehlern mit der E-Mail-Schnittstelle.</a>
  <li><a href="server-refcard">Referenzkarte des Mailservers.</a>
  <li><a href="server-request">Anfordern von Fehlern per E-Mail.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
