# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=ports/beowulf
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/beowulf/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml
