#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="beowulf">
   [EN:Debian for Beowulf:]
   [AR:Debian for Beowulf:]
   [CA:Debian per a Beowulf:]
   [DA:Debian til Beowulf:]
   [DE:Debian für Beowulf:]
   [EL:Debian for Beowulf:]
   [EO:Debian for Beowulf:]
   [ES:Debian para Beowulf:]
   [FI:Debian for Beowulf:]
   [FR:Debian pour Beowulf:]
   [HR:Debian za Beowulf:]
   [HU:Debian for Beowulf:]
   [IT:Debian per Beowulf:]
   [JA:Debian for Beowulf:]
   [KO:Debian for Beowulf:]
   [NL:Debian for Beowulf:]
   [NO:Debian for Beowulf:]
   [PL:Debian for Beowulf:]
   [PT:Debian para Beowulf:]
   [RO:Debian for Beowulf:]
   [RU:Debian for Beowulf:]
   [SV:Debian för Beowulf:]
   [TR:Debian for Beowulf:]
   [ZH:Debian for Beowulf:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="beowulf"       basename="index">

