#use wml::debian::submenu

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<menu-item basename="../index">
[EN:Ports:]
[AR:Ports:]
[DA:Tilpasninger:]
[DE:Ports:]
[EL:Ports:]
[EO:Ports:]
[ES:Migraciones:]
[FI:Ports:]
[FR:Ports:]
[HR:Ports:]
[HU:Ports:]
[IT:Ports:]
[JA:Ports:]
[KO:Ports:]
[NL:Ports:]
[NO:Porteringer:]
[PL:Ports:]
[PT:Ports:]
[RO:Ports:]
[RU:Ports:]
[SV:Anpassningar:]
[TR:Ports:]
[ZH:Ports:]
</menu-item>

<menu-item basename="index">
[EN:Debian for Sparc64:]
[AR:Debian for Sparc64:]
[DA:Debian til Sparc64:]
[DE:Debian für Sparc64:]
[EL:Debian for Sparc64:]
[EO:Debian for Sparc64:]
[ES:Debian para Sparc64:]
[FI:Debian for Sparc64:]
[FR:Debian for Sparc64:]
[HR:Debian for Sparc64:]
[HU:Debian for Sparc64:]
[IT:Debian per Sparc64:]
[JA:Debian for Sparc64:]
[KO:Debian for Sparc64:]
[NL:Debian for Sparc64:]
[NO:Debian for Sparc64:]
[PL:Debian for Sparc64:]
[PT:Debian para Sparc64:]
[RO:Debian for Sparc64:]
[RU:Debian for Sparc64:]
[SV:Debian för Sparc64:]
[TR:Debian for Sparc64:]
[ZH:Debian for Sparc64:]
</menu-item>

