#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"

# Please keep slices sorted alphabetically so it's easier to detect
# languages in them (except english ones).

<define-menu-item name="sparc64">
   [EN:Debian for Sparc64:]
   [AR:Debian for Sparc64:]
   [DA:Debian til Sparc64:]
   [DE:Debian für Sparc64:]
   [EL:Debian for Sparc64:]
   [EO:Debian for Sparc64:]
   [ES:Debian para Sparc64:]
   [FI:Debian for Sparc64:]
   [FR:Debian pour Sparc64:]
   [HR:Debian za Sparc64:]
   [HU:Debian for Sparc64:]
   [IT:Debian per Sparc64:]
   [JA:Debian for Sparc64:]
   [KO:Debian for Sparc64:]
   [NL:Debian for Sparc64:]
   [NO:Debian for Sparc64:]
   [PL:Debian for Sparc64:]
   [PT:Debian para Sparc64:]
   [RO:Debian for Sparc64:]
   [RU:Debian for Sparc64:]
   [SV:Debian för Sparc64:]
   [TR:Debian for Sparc64:]
   [ZH:Debian for Sparc64:]
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="sparc64"       basename="index">

