# If this makefile is not generic enough to support a translation,
# please contact debian-www.

WMLBASE=../..
CUR_DIR=international/Polish
SUBS=

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: index.wml $(ENGLISHSRCDIR)/international/index.data
