# This Makefile should need no changes from webwml/english/Pics/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=Pics
SUBS=

include $(WMLBASE)/Make.lang

# I have no idea what this is for and it is breaking the build
# explain why on debian-www if you uncomment this - Jay
# $(ENGLISHSRCDIR)
# 
# cp -siv /english/Pics/red-*.png .
