#use wml::debian::submenu
#include "$(ENGLISHDIR)/ports/menu.defs"


<define-menu-item name="sparc">
  <gettext domain="ports">Debian for Sparc</gettext>
</define-menu-item>

<menu-item name="ports"         basename="../index">
<menu-item name="sparc"         basename="index">
<menu-item name="credits"       basename="credits">
<menu-item name="porting"       basename="porting">
<menu-item name="problems"      basename="problems">

