#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Debian&nbsp;Hamradio&nbsp;Blandning</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">Om</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Nyhets-&nbsp;Arkiv</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Kontakt</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Hämta&nbsp;Blandningen</a>
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Hämta&nbsp;live-&nbsp;avbildningar</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Använda&nbsp;metapaketen</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Dokumentation</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Debian&nbsp;Hamradio-&nbsp;handbok</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Support</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Utveckling</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Hamradio Underhållargrupp</a></li>
        <li><a href="<hamradio-maintguide-html/>">Hamradio Underhållarguide</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Skoj</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/blends/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
