# This Makefile should need no changes from webwml/english/security/audit/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=security/audit
SUBS=

GETTEXTFILES += others.mo

include $(WMLBASE)/Make.lang


index.$(LANGUAGE).html: index.wml  Makefile
	$(WML) $(<F)

faq.$(LANGUAGE).html: faq.wml  Makefile
	$(WML) $(<F)

maintainers.$(LANGUAGE).html: maintainers.wml  Makefile
	$(WML) $(<F)

packages.$(LANGUAGE).html: packages.wml  Makefile
	$(WML) $(<F)

tools.$(LANGUAGE).html: tools.wml  Makefile
	$(WML) $(<F)

advisorises.$(LANGUAGE).html: advisorises.wml  Makefile
	$(WML) $(<F)

auditing.$(LANGUAGE).html: auditing.wml  Makefile
	$(WML) $(<F)
