# This Makefile should need no changes from webwml/catalan/international/Catalan/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=international/Catalan
SUBS=

include $(WMLBASE)/Make.lang

