{#style#:
    <style type="text/css">
      address                  {
      	color: gray; 
        background-color: white;
      	margin-left: -2em;
      	text-align: right;
      }     
      
      h1.center                { text-align: center;  }
      h1.title                 {
      	text-align: center; 
      	font-weight: bold; 
        text-shadow: 0.3em 0.3em 0.1em #F00;
      }
      div.center {text-align: center}
      p.x-small {font-size: x-small}
      ul.spacey li {padding-top: 0.5ex; padding-bottom: 0.5ex}

      .titletext               {
      	 color: black;
         background-color: white;
      	 font-size: 18pt;
      	 font-weight: bold;
      	 margin-bottom: -10px;
      }
      p.initial:first-letter {font-size: 215%; float: left }
      p + p { text-indent: 2em }
     table.mainbody {
            border-collapse:        collapse;
            border:         outset 2pt #8cacbb;/*   1px solid #8cacbb;*/
            margin-left: auto;
            margin-right: auto;
            margin-top: 1.5em;
            margin-bottom: 1.0em;
            clear:                  both;
          }
     table.mainbody th {
            background:             #DEE7EC;
            border-top:             1px solid #8CACBB;
            border-bottom:          1px solid #8CACBB;
            border-right:           1px solid #8CACBB;
            color:                  Black;
            font-weight:            normal;
            padding:                         0em 1em 0em 1em;
            white-space:            nowrap;
            text-align:             left;
          }
     table.mainbody td {
            border-right:           1px solid #8CACBB;
            border-bottom:           1px solid #8CACBB;
            padding:                0.5em;
            text-align:             left;
          }
     .Ignored { 
       color: rgb(136, 125, 107);
       text-align: center;
         }

     p.note                   {
         color: green;
         margin-left: 1em;
     }

    </style>
:##}
