# This Makefile should need no changes from webwml/english/ports/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=ports
SUBS=sparc alpha arm powerpc mips sparc64

include $(WMLBASE)/Make.lang

