# This Makefile should need no changes from webwml/english/MailingLists/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=..
CUR_DIR=MailingLists
SUBS=

include $(WMLBASE)/Make.lang


subscribe.sv.html: subscribe.wml ../../english/MailingLists/subscribe.wml
	$(WML) subscribe.wml

unsubscribe.sv.html: unsubscribe.wml ../../english/MailingLists/unsubscribe.wml
	$(WML) unsubscribe.wml
