<p>Altre pagine BTS (sistema di gestione delle anomalie)

<ul>
  <li><a href="./">Pagina principale del sistema di tracciamento.</a>
  <li><a href="Reporting">Istruzioni per segnalare le anomalie.</a>
  <li><a href="Access">Accedere ai log del sistema in maniera diversa
      dal WWW.</a>
  <li><a href="Developer">Informazioni per sviluppatori sul sistema
      di tracciamento delle anomalie.</a>
  <li><a href="server-control">Informazioni agli sviluppatori sulla
      manipolazione delle segnalazioni tramite l'interfaccia e-mail.</a>
  <li><a href="server-refcard">Carta di riferimento per il mailserver.</a>
  <li><a href="server-request">Richiedere segnalazioni via e-mail.</a>
</ul>
