<small>
  <ul>
  <li>Flag:
  <input type="radio" name="archive" value="no" checked> anomalie non risolte 
  <input type="radio" name="archive" value="yes"> anomalie archiviate
  <input type="checkbox" name="raw" value="yes">Senza ordine di status o di gravità
  <li>Ordine inverso di:
  <input type="checkbox" name="sev-rev" value="yes">status
  <input type="checkbox" name="pend-rev" value="yes">gravità
  <input type="checkbox" name="bug-rev" value="yes">anomalie
  <li>Status inclusi:
  <input type="checkbox" name="pend-inc" value="pending">Open
  <input type="checkbox" name="pend-inc" value="forwarded">Forwarded
  <input type="checkbox" name="pend-inc" value="pending-fixed">Pending
  <input type="checkbox" name="pend-inc" value="fixed">Fixed
  <input type="checkbox" name="pend-exc" value="done">Done
  <li>Status esclusi:
  <input type="checkbox" name="pend-exc" value="pending">Open
  <input type="checkbox" name="pend-exc" value="forwarded">Forwarded
  <input type="checkbox" name="pend-exc" value="pending-fixed">Pending
  <input type="checkbox" name="pend-exc" value="fixed">Fixed
  <input type="checkbox" name="pend-exc" value="done">Done
  <li>Gravità incluse:
  <input type="checkbox" name="sev-inc" value="critical">Critical
  <input type="checkbox" name="sev-inc" value="grave">Grave
  <input type="checkbox" name="sev-inc" value="serious">Serious
  <input type="checkbox" name="sev-inc" value="important">Important
  <input type="checkbox" name="sev-inc" value="normal">Normal
  <input type="checkbox" name="sev-inc" value="minor">Minor
  <input type="checkbox" name="sev-inc" value="wishlist">Wishlist
  <input type="checkbox" name="sev-inc" value="fixed">Fixed
  <li>Gravità escluse:
  <input type="checkbox" name="sev-exc" value="critical">Critical
  <input type="checkbox" name="sev-exc" value="grave">Grave
  <input type="checkbox" name="sev-exc" value="serious">Serious
  <input type="checkbox" name="sev-exc" value="important">Important
  <input type="checkbox" name="sev-exc" value="normal">Normal
  <input type="checkbox" name="sev-exc" value="minor">Minor
  <input type="checkbox" name="sev-exc" value="wishlist">Wishlist
  <input type="checkbox" name="sev-exc" value="fixed">Fixed
  </ul>
  </small>
