# This Makefile should need no changes from webwml/english/ports/i386/Makefile
# Please send a message to debian-www if you need to modify anything, so the
# problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/i386
SUBS=

include $(WMLBASE)/Make.lang

