<p>Andre sider i feilrapporteringssystemet

<ul>
  <li><A href="./">Forsiden til feilrapportsystemet.</A>
  <li><A href="Reporting">Hvordan rapportere feil.</A>
  <li><A href="Access">Komme til loggene på annet måter enn via web.</A>
  <li><A href="Developer">Bruksansvisning for utviklere.</A>
  <li><A href="server-control">Informasjon om hvordan man jobber med
  feilrapporter via epost.</A>
  <li><A href="server-refcard">Referansekort for epost-tjeneren.</A>
  <li><A href="server-request">Etterspør feilrapporter via epost.</A>
# <li><A href="db/ix/full.html">Komplett liste over ikke rettede og
#  nye feilrapporter.</A>
# <li><A href="db/ix/packages.html">Pakker med rapporter om feil.</A>
# <li><A href="db/ix/maintainers.html">Ansvarlige for pakker med
#  feilrapporter.</A>
</ul>
