<p>Other BTS pages:

<ul>
  <li><a href="./">Página principal dos conteúdos do sistema de gerenciamento de bugs.</a>
  <li><a href="Reporting">Instruções para reportar bugs.</a>
  <li><a href="Access">Acessando os logs do sistema de gerenciamento de bugs.</a>
  <li><a href="Developer">Informações para desenvolvedor no sistema de gerenciamento 
  de bugs.</a>
  <li><a href="server-control">Informações do desenvolvedor na manipulação
      de bugs usando a interface de controle de e-mail.</a>
  <li><a href="server-refcard">Cartão de referência de servidores de mail.</a>
  <li><a href="server-request">Requisitando reports de bug pelo e-mail.</a>
#  <li><a href="db/ix/full.html">Full list of outstanding and recent bug
#      reports.</a>
#  <li><a href="db/ix/packages.html">Packages with bug reports.</a>
#  <li><a href="db/ix/maintainers.html">Maintainers of packages with bug
#      reports.</a>
</ul>
