# This Makefile should need no changes from webwml/english/international/Chinese/faq/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE = ../../..
CUR_DIR = international/Chinese/faq
SUBS =

include $(WMLBASE)/Make.lang
