# This Makefile should need no changes from webwml/english/ports/kfreebsd-gnu/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE=../..
CUR_DIR=ports/kfreebsd-gnu
SUBS=

include $(WMLBASE)/Make.lang

$(HTMLFILES): $(ENGLISHSRCDIR)/ports/kfreebsd-gnu/menu.inc $(TEMPLDIR)/submenu.wml $(TEMPLDIR)/template.wml