#!/usr/bin/perl -w

# This script must be setuid and owned by treacy:distmnt

# Note: actual checking out and building is done through
#   /debian2/private/project/Distmnt-web/web_3_wml
# which is run with run-parts by maor's crontab on master

# update the webwml repository and run a make on all the language
# directories

$WML_DIR = '/debian2/web/webwml';

$< = $>;
$ENV{PATH} = "/bin:/usr/bin";
$ENV{HOME} = "/debian/home/treacy";

chdir $WML_DIR;
system("cvs update -d");

system("make");
exit;
