#!/usr/bin/perl -w

# This script must be setuid and owned by treacy:distmnt

# update the webwml repository and run a make on all the language
# directories

$WML_DIR = '/debian2/web/webwml';

$< = $>;
$ENV{PATH} = "/bin:/usr/bin";
$ENV{HOME} = "/debian/home/treacy";

chdir $WML_DIR;
system("cvs update -d");

system("make");
exit;

