#use wml::debian::blends::hamradio

{#alternate_navbar#:
   <div id="second-nav">
      <p><a href="$(HOME)/blends/hamradio/">Debian&nbsp;Hamradio&nbsp;Blend</a></p>
    <ul>
      <li><a href="$(HOME)/blends/hamradio/about">Acerca de</a></li>
      <li><a href="$(HOME)/blends/hamradio/News/">Archivos&nbsp;de&nbsp;noticias</a></li>
      <li><a href="$(HOME)/blends/hamradio/contact">Contactar</a></li>
      <li><a href="$(HOME)/blends/hamradio/get/">Obtener&nbsp;la&nbsp;mezcla</a>
         <ul>
         <li><a href="$(HOME)/blends/hamradio/get/live">Descargar&nbsp;imagen&nbsp;«en vivo»</a></li>
         <li><a href="$(HOME)/blends/hamradio/get/metapackages">Usar&nbsp;los&nbsp;metapaquetes</a></li>
	 </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/docs/">Documentación</a>
        <ul>
        <li><a href="<hamradio-handbook-html/>">Manual&nbsp;de&nbsp;Debian&nbsp;Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/support">Soporte</a></li>
      <li><a href="$(HOME)/blends/hamradio/dev">Desarrollo</a>
        <ul>
        <li><a href="https://wiki.debian.org/DebianHams">Equipo de mantenedores de Hamradio</a></li>
        <li><a href="<hamradio-maintguide-html/>">Guía para mantenedores de Hamradio</a></li>
        </ul>
      </li>
      <li><a href="$(HOME)/blends/hamradio/fun">Diversión</a></li>
      <li><a href="https://twitter.com/DebianHamradio"><img src="$(HOME)/blends/hamradio/Pics/twitter.gif" alt="Twitter" width="80" height="15"></a></li>
    </ul>
   </div>
:#alternate_navbar#}
