# This Makefile should need no changes from webwml/english/international/Chinese/Makefile
# Please send a message to debian-www if you need to modify anything
# so the problem can be fixed.

WMLBASE = ../..
CUR_DIR = international/Chinese
SUBS = devel doc faq News screenshot

include $(WMLBASE)/Make.lang


index.zh-cn.html index.zh-hk.html index.zh-tw.html: index.wml News/index.wml
