LANG=it
HTMLDIR=../../debian.org
TEMPLDIR=template/debian
ENGLISHSRCDIR=../english
# EPILOG=--epilog=weblint
$(HTMLDIR)/%.html.$(LANG) : %.wml $(TEMPLDIR)/template.wml
	cd $(<D) && wml $(EPILOG) $(<F)
# cd $(<D) && wml -o $@ $(EPILOG) $(<F)

# translators should comment out the line for any file they haven't translated.
all:\
	$(HTMLDIR)/contact.html.$(LANG) \
	$(HTMLDIR)/index.html.$(LANG) \
	$(HTMLDIR)/license.html.$(LANG) \
	$(HTMLDIR)/social_contract.html.$(LANG) \
	$(HTMLDIR)/support.html.$(LANG) \
	$(HTMLDIR)/developers_corner.html.$(LANG) \
	$(HTMLDIR)/2.0/errata.html.$(LANG) \
        $(HTMLDIR)/2.0/2.0beta_CD.html.$(LANG) \
        $(HTMLDIR)/2.0/HOWTO.upgrade.html.$(LANG) \
	$(HTMLDIR)/MailingLists/debian-announce.html.$(LANG) \
	$(HTMLDIR)/devel/HOWTO_translate.html.$(LANG) \
	$(HTMLDIR)/devel/extract_key.html.$(LANG) \
	$(HTMLDIR)/devel/help.html.$(LANG) \
	$(HTMLDIR)/devel/incoming_mirrors.html.$(LANG) \
	$(HTMLDIR)/devel/maintainer_contacts.html.$(LANG) \
	$(HTMLDIR)/devel/mirror.html.$(LANG) \
	$(HTMLDIR)/devel/people.html.$(LANG) \
	$(HTMLDIR)/devel/release_info.html.$(LANG) \
	$(HTMLDIR)/devel/rsync_examples.html.$(LANG) \
	$(HTMLDIR)/intro/about.html.$(LANG) \
	$(HTMLDIR)/intro/cooperation.html.$(LANG) \
	$(HTMLDIR)/intro/international.html.$(LANG) \
	$(HTMLDIR)/intro/license_disc.html.$(LANG) \
	$(HTMLDIR)/intro/cn.html.$(LANG) \
	$(HTMLDIR)/intro/free.html.$(LANG) \
	$(HTMLDIR)/intro/why_debian.html.$(LANG) \
	$(HTMLDIR)/logos/index.html.$(LANG) \
	$(HTMLDIR)/security/index.html.$(LANG) \
#    $(HTMLDIR)/MailingLists/subscribe.html.$(LANG) \
#    $(HTMLDIR)/MailingLists/unsubscribe.html.$(LANG) \		
#    $(HTMLDIR)/devel/mirror_submit.html.$(LANG) \
#    $(HTMLDIR)/devel/ports.html.$(LANG) \
#    $(HTMLDIR)/donations.html.$(LANG) \
#    $(HTMLDIR)/news.html.$(LANG) \
#    $(HTMLDIR)/news1997.html.$(LANG) \
#    $(HTMLDIR)/related_links.html.$(LANG) \
#    $(HTMLDIR)/doc/index.html.$(LANG) \
#    $(HTMLDIR)/distrib/distrib.html.$(LANG) \
#    $(HTMLDIR)/distrib/ftplist.html.$(LANG) \
#    $(HTMLDIR)/distrib/packages.html.$(LANG) \
#    $(HTMLDIR)/distrib/vendors.html.$(LANG) \
#    $(HTMLDIR)/


#
# TRANSLATORS SHOULD NOT HAVE TO TOUCH ANYTHING BELOW THIS LINE
#

$(HTMLDIR)/index.html.$(LANG): index.wml ../english/news.wml $(TEMPLDIR)/mainpage.wml $(TEMPLDIR)/ctime.wml
	wml index.wml

# with no rule, the default ruleset (at the top) is used
$(HTMLDIR)/devel/people.html.$(LANG): devel/people.wml $(ENGLISHSRCDIR)/devel/people.names


# template dependencies

template/debian/basic.wml: template/debian/navbar.wml
	touch template/debian/basic.wml

template/debian/footer.wml: template/debian/ctime.wml
	touch template/debian/footer.wml

# template/debian/languages.wml: template/debian/
# 	touch template/debian/languages.wml

template/debian/menubar.wml: template/debian/footer.wml
	touch template/debian/menubar.wml

# template/debian/recent_news.wml: template/debian/
# 	touch template/debian/recent_news.wml

# template/debian/ctime.wml: template/debian/
# 	touch template/debian/ctime.wml

template/debian/mainpage.wml: template/debian/basic.wml template/debian/menubar.wml
	touch template/debian/mainpage.wml

# template/debian/navbar.wml: template/debian/
# 	touch template/debian/navbar.wml

template/debian/template.wml: template/debian/basic.wml template/debian/footer.wml
	touch template/debian/template.wml

people: devel/people.wml
	cd devel && wml people.wml
